CREATE TABLE CG_AREA (
ID_AREA INT NOT NULL,
DESC_AREA VARCHAR(50) NOT NULL,
ID_RESPONSAVEL INT NOT NULL, 
USER_INS INT NULL, 
DATA_INS DATETIME NULL, 
USER_UPD INT NULL, 
DATA_UPD DATETIME NULL )
GO

ALTER TABLE CG_AREA 
ADD CONSTRAINT PK_CG_AREA PRIMARY KEY (ID_AREA)
GO

ALTER TABLE CG_AREA 
ADD CONSTRAINT FK_CG_AREA_RESPONSAVEL 
FOREIGN KEY (ID_RESPONSAVEL) REFERENCES CG_RESPONSAVEL (ID_RESPONSAVEL)
GO

ALTER TABLE CG_AREA 
ADD CONSTRAINT UNQ_DESC_AREA UNIQUE (DESC_AREA)
GO
