INSERT INTO CG_AREA
VALUES (0, 'NÃO DEFINIDO', 1,1,GETDATE(),1,GETDATE())
GO

alter table CG_LOJA
add LOJA_FISICA BIT NOT NULL DEFAULT(0),
    PARCERIA	 BIT NOT NULL DEFAULT(0),
    ID_AREA     INT NOT NULL DEFAULT(0)
GO

alter table CG_LOJA
ADD CONSTRAINT FK_CG_LOJA_CG_AREA_01 FOREIGN KEY (ID_AREA) 
REFERENCES CG_AREA (ID_AREA)
GO


