CREATE TABLE CG_OCORRENCIA (
ID_OCORRENCIA INT NOT NULL,
DATA_OCORRENCIA DATETIME NOT NULL,
DESCRICAO VARCHAR(60) NOT NULL,
ID_EQUIPAMENTO INT NOT NULL,
SERIE VARCHAR(30) NOT NULL,
ID_LOJA INT NOT NULL,
HISTORICO TEXT NOT NULL,
USER_INS INT NULL,
DATA_INS DATETIME NULL,
USER_UPD INT NULL,
DATA_UPD DATETIME NULL )
GO

ALTER TABLE CG_OCORRENCIA 
ADD CONSTRAINT PK_CG_OCORRENCIA PRIMARY KEY (ID_OCORRENCIA)
GO

ALTER TABLE CG_OCORRENCIA
ADD CONSTRAINT FK_CG_OCORRENCIA_CG_EQUIPAMENTO_01 FOREIGN KEY (ID_EQUIPAMENTO)
REFERENCES CG_EQUIPAMENTO (ID_EQUIPAMENTO)
GO

ALTER TABLE CG_OCORRENCIA
ADD CONSTRAINT FK_CG_OCORRENCIA_CG_LOJA_01 FOREIGN KEY (ID_LOJA)
REFERENCES CG_LOJA (ID_LOJA)
GO

