INSERT INTO CG_MODULO (ID_MODULO, DESC_MODULO, USER_INS, DATA_INS, USER_UPD, DATA_UPD)
VALUES (51, 'PARAMETRIZAÇÃO DE PESQUISAS', 1, GETDATE(), 1, GETDATE())
GO

UPDATE CG_SEQUENCIAL
SET KEYID = 51 
WHERE TABELA = 'CG_MODULO'
GO