USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_LOJA]    Script Date: 16/07/2017 16:10:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[VW_CG_LOJA]
AS
SELECT A.ID_LOJA,
       A.SIGLA,
       A.NOME,
       A.ENDERECO,
       A.COMPLEMENTO,
       A.CEP,
       A.CIDADE,
       A.BAIRRO,
       A.UF,
       A.ID_TIPO_LOCAL,
       B.DESC_ALOCACAO,
       A.ID_RESPONSAVEL,
       C.NOME AS RESPONSAVEL,
       C.APELIDO,
	  A.CODIGO, 
	  A.TELEFONE,
	  A.CELULAR, 
	  A.ID_AREA,
	  D.DESC_AREA,
	  A.LOJA_FISICA,
	  A.PARCERIA,
	  D.ID_RESPONSAVEL AS ID_RESPONSAVEL_AREA,
	  E.NOME AS RESPONSAVEL_AREA
FROM 
	CG_LOJA AS A (NOLOCK)
LEFT JOIN 
	dbo.CG_ALOCACAO AS B (NOLOCK)
		ON A.ID_TIPO_LOCAL = B.ID_ALOCACAO
LEFT JOIN 
	dbo.CG_RESPONSAVEL AS C (NOLOCK)
		ON A.ID_RESPONSAVEL = C.ID_RESPONSAVEL
LEFT JOIN 
    dbo.CG_AREA AS D (NOLOCK)
		ON D.ID_AREA = A.ID_AREA
LEFT JOIN 
	dbo.CG_RESPONSAVEL AS E (NOLOCK)
		ON D.ID_RESPONSAVEL = E.ID_RESPONSAVEL

GO


