insert into CG_MODULO (ID_MODULO,DESC_MODULO,USER_INS,DATA_INS,USER_UPD,DATA_UPD)
VALUES (54, 'CADASTRO DE OCORRÊNCIAS', 1,GETDATE(),1,GETDATE())
GO

INSERT INTO CG_SEQUENCIAL (TABELA, KEYID, USER_INS, DATA_INS, USER_UPD, DATA_UPD)
VALUES ('CG_OCORRENCIA',0,1,GETDATE(),1,GETDATE())
GO

