USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_MOVIMENTO_EQUIPAMENTO_QUARENTENA_ITEM]    Script Date: 19/08/2017 15:15:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_CG_MOVIMENTO_EQUIPAMENTO_QUARENTENA_ITEM] 
AS
SELECT A.ID_ROMANEIO,
       A.UNIQUE_KEYID,
       A.ID_EQUIPAMENTO,
       B.DESC_EQUIPAMENTO,
       B.SERIE,
       B.MODELO,
       A.QTD,
       A.VALOR,
	  A.TRANSITO
FROM 
	CG_MOVIMENTO_EQUIPAMENTO_QUARENTENA_ITEM AS A
LEFT JOIN 
	CG_EQUIPAMENTO AS B 
		ON A.ID_EQUIPAMENTO = B.ID_EQUIPAMENTO

GO


