USE dbCG
GO

INSERT INTO CG_TIPO_LOCAL_ESTOQUE (ID_TIPO_LOCAL_ESTOQUE, DESC_TIPO_LOCAL_ESTOQUE)
VALUES (-11, 'RESERVA VENDA'),(-12, 'VENDIDO')
GO

INSERT INTO CG_LOJA (ID_LOJA,SIGLA,NOME,ENDERECO,COMPLEMENTO,CEP,CIDADE,BAIRRO,
						UF,ID_TIPO_LOCAL,ID_RESPONSAVEL,USER_INS,DATA_INS,USER_UPD,DATA_UPD,
						TELEFONE,CELULAR,LOJA_FISICA,PARCERIA,ID_AREA,ID_EMPRESA,ID_TIPO_LOCAL_ESTOQUE,
						INATIVO,ULTIMA_ATUALIZACAO,INICIO_VIGENCIA,CODIGO)
VALUES
(-11,'RESERVA VENDA','RESERVA VENDA','ENDERECO DA MATRIZ','','-','SAO PAULO','TATUAPE','SP',1,1,1,
	GETDATE(),1,GETDATE(),'-','-',0,0,'0000',1,-11,0,GETDATE(),GETDATE(),'R011'),
(-12,'VENDIDO','VENDIDO','ENDERECO DA MATRIZ','','-','SAO PAULO','TATUAPE','SP',1,1,1,
	GETDATE(),1,GETDATE(),'-','-',0,0,'0000',1,-12,0,GETDATE(),GETDATE(),'R012')





