USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_EQUIPAMENTO]    Script Date: 26/11/2018 08:33:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER VIEW [dbo].[VW_CG_EQUIPAMENTO]
AS
SELECT A.ID_EQUIPAMENTO,
       A.DESC_EQUIPAMENTO,
       A.SERIE,
       A.MODELO,
       A.ID_TIPO_EQUIPAMENTO,
       B.DESC_TIPO_EQUIPAMENTO,
       A.ID_FORNECEDOR,
       C.SIGLA,
       C.UTILIZA_NFTS,
       C.NOME,
       A.PROTOCOLO,
       A.VALOR,
       A.OBS,
	  A.ID_CONTROLE,
	  A.NF_ENTRADA,
	  A.DATA_NF, 
	  A.PRAZO_GARANTIA,
	  A.ID_ULTIMA_OS,
	  A.DATA_INICIO_GARANTIA,
	  A.DATA_TERMINO_GARANTIA,
	  A.ID_LOCAL_ESTOQUE,
	  A.TIPO_LOCAL,
	  A.ID_EMPRESA,
	  a.PRECO_VENDA
FROM 
	CG_EQUIPAMENTO AS A (NOLOCK)
LEFT JOIN 
	CG_TIPO_EQUIPAMENTO AS B (NOLOCK)
		ON A.ID_TIPO_EQUIPAMENTO = B.ID_TIPO_EQUIPAMENTO
LEFT JOIN 
	CG_FORNECEDOR AS C (NOLOCK)
		ON A.ID_FORNECEDOR = C.ID_FORNECEDOR





GO


