/* sp_ComandoListarSQL CG_CARGO */
ALTER PROCEDURE sp_ComandoListarSQL
@TABELA VARCHAR(50)
AS
BEGIN

DECLARE @I INT
DECLARE @TOT INT
DECLARE @COMANDO VARCHAR(8000)
DECLARE @COLUNA VARCHAR(50)
DECLARE @VIRGULA VARCHAR(10)

SELECT 
	IDENTITY(INT,1,1) AS ID, 
	TABELA, 
	COLUNA, 
	IDCOLUNA, 
	ORDERCOL, 
	CHAVE, 
	TIPODADO, 
	COLUNA_FILTRO, 
	APELIDO_COLUNA, 
	MOSTRA_COLUNA
INTO #TMPPESQ
FROM 
	CG_PARAMETRO_PESQUISA_DINAMICA
WHERE 
	TABELA = @TABELA
	AND MOSTRA_COLUNA = 1
ORDER BY 	ORDERCOL

SET @TOT = @@ROWCOUNT
SET @I = 1
SET @COMANDO = 'SELECT '

WHILE @I <= @TOT
BEGIN

	SELECT @COLUNA = RTRIM(LTRIM(COLUNA)) 
	FROM #TMPPESQ 
	WHERE ID = @I
	SET @VIRGULA = CASE
					WHEN @I<@TOT THEN ','
					ELSE ' '
					END

	 SET @COMANDO = @COMANDO + LTRIM(RTRIM(@COLUNA)) + @VIRGULA
	 SET @I = @I + 1		
END

SELECT @COMANDO + ' FROM ' + @TABELA AS COMANDO

END
