ALTER PROCEDURE sp_Valida_Chip_Entrada
@SIMID VARCHAR(20)
AS

DECLARE @ERRO BIT, @MSG VARCHAR(100)
SET @ERRO = 0
SET @MSG = ''

IF NOT EXISTS(SELECT 1 FROM [dbo].[VW_CG_CHIP_DISPONIVEIS_ENTRADA_MATRIZ]
    WHERE SIMID = @SIMID)
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM CG_CHIP WHERE SIMID = @SIMID)
    BEGIN
	   SET @ERRO = 1
	   SET @MSG = 'CHIP NÃO CADASTRADO NO BANCO DE DADOS'
    END
    ELSE 
    BEGIN
	   IF EXISTS (SELECT 1 FROM CG_ESTOQUE_CHIP 
				INNER JOIN CG_CHIP ON CG_CHIP.ID_CHIP = CG_ESTOQUE_CHIP.ID_CHIP
				WHERE CG_CHIP.SIMID = @SIMID AND CG_ESTOQUE_CHIP.ID_LOCAL <> 0)
	   BEGIN
		  SET @ERRO = 1
		  SET @MSG = 'CHIP JÁ CADASTRADO NO BANCO DE DADOS'
	   END
    END
END

IF @ERRO = 1
BEGIN
    RAISERROR(@MSG, 16, 1)
END
ELSE
BEGIN
    select 
	   a.ID_CHIP, 
	   a.SIMID, 
	   a.ID_OPERADORA, 
	   a.DESC_OPERADORA, 
	   b.CUSTO 
    from 
	   VW_CG_CHIP_DISPONIVEIS_ENTRADA_MATRIZ A
    inner join CG_CHIP B 
		  ON B.ID_CHIP = A.ID_CHIP
    where a.SIMID = @SIMID
END



