ALTER PROCEDURE sp_Valida_Equipamento_Entrada
@DESC_EQUIPAMENTO VARCHAR(50)
AS

DECLARE @ERRO BIT, @MSG VARCHAR(100)
SET @ERRO = 0
SET @MSG = ''

IF NOT EXISTS(SELECT 1 FROM [dbo].[VW_CG_EQUIPAMENTO_DISPONIVEIS_ENTRADA_MATRIZ]
    WHERE DESC_EQUIPAMENTO = @DESC_EQUIPAMENTO)
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM CG_EQUIPAMENTO WHERE DESC_EQUIPAMENTO = @DESC_EQUIPAMENTO)
    BEGIN
	   SET @ERRO = 1
	   SET @MSG = 'EQUIPAMENTO NÃO CADASTRADO NO BANCO DE DADOS'
    END
    ELSE 
    BEGIN
	   IF EXISTS (SELECT 1 FROM CG_ESTOQUE_EQUIPAMENTO 
				INNER JOIN CG_EQUIPAMENTO ON CG_EQUIPAMENTO.ID_EQUIPAMENTO = CG_ESTOQUE_EQUIPAMENTO.ID_EQUIPAMENTO
				WHERE CG_EQUIPAMENTO.DESC_EQUIPAMENTO = @DESC_EQUIPAMENTO 
					   AND CG_ESTOQUE_EQUIPAMENTO.ID_LOCAL <> 0)
	   BEGIN
		  SET @ERRO = 1
		  SET @MSG = 'EQUIPAMENTO JÁ CADASTRADO NO BANCO DE DADOS'
	   END
    END
END

IF @ERRO = 1
BEGIN
    RAISERROR(@MSG, 16, 1)
END
ELSE
BEGIN
    select 
	   a.ID_EQUIPAMENTO, 
	   a.DESC_EQUIPAMENTO,
	   a.SERIE, 
	   a.MODELO, 
	   b.VALOR 
    from 
	   VW_CG_EQUIPAMENTO_DISPONIVEIS_ENTRADA_MATRIZ A
    inner join CG_EQUIPAMENTO B 
		  ON B.ID_EQUIPAMENTO = A.ID_EQUIPAMENTO
    where a.DESC_EQUIPAMENTO = @DESC_EQUIPAMENTO
END



