CREATE PROCEDURE spDatasEstoqueEquipamentos
as
BEGIN
    DECLARE @DATAS TABLE (DATAMOV VARCHAR(10) NULL)

    INSERT @DATAS 
    select DISTINCT CONVERT(VARCHAR,DATAMOV,103) AS DATAMOV 
    from CG_ESTOQUE_EQUIPAMENTO

    INSERT @DATAS VALUES ('TODAS')

    SELECT DATAMOV FROM @DATAS ORDER BY DATAMOV DESC
END
