/* EXEC spListaAcessoUsuario 1 */
ALTER PROCEDURE SPLISTAACESSOUSUARIO
@ID_USUARIO INT
AS
BEGIN
	SELECT 
		M.ID_MODULO, 
		M.DESC_MODULO, 
		@ID_USUARIO AS ID_USUARIO, 
		APELIDO=(SELECT U.APELIDO FROM CG_USUARIO U WHERE U.ID_USUARIO=@ID_USUARIO), 
		NOME=(SELECT U.NOME FROM CG_USUARIO U WHERE U.ID_USUARIO=@ID_USUARIO),  
		PERMISSAO = ISNULL((SELECT A.PERMISSAO 
								FROM CG_ACESSO A WHERE A.ID_USUARIO=@ID_USUARIO 
								AND A.ID_MODULO=M.ID_MODULO),'S')
	FROM 
		CG_MODULO M
END