ALTER TABLE CG_LOJA
ADD TELEFONE2 VARCHAR(20) NULL,
	CELULAR2 VARCHAR(20) NULL,
	CELULAR3 VARCHAR(20) NULL,
	CELULAR4 VARCHAR(20) NULL,
	CELULAR5 VARCHAR(20) NULL,
	CELULAR6 VARCHAR(20) NULL,
	INATIVO  BIT NOT NULL CONSTRAINT DF_INATIVO_CG_LOJA DEFAULT(0),
	ULTIMA_ATUALIZACAO DATETIME NOT NULL CONSTRAINT DF_ULT_ATUALIZACAO_CG_LOJA DEFAULT(GETDATE()),
	INICIO_VIGENCIA DATETIME NULL,
	FINAL_VIGENCIA DATETIME NULL
GO

UPDATE CG_LOJA SET ULTIMA_ATUALIZACAO=DATA_INS, INICIO_VIGENCIA=DATA_INS
GO


