USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_LOJA]    Script Date: 01/06/2018 08:46:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW [dbo].[VW_CG_LOJA_HISTORICO]
AS


SELECT A.ID_HISTORICO,
	   A.ID_LOJA,
       A.SIGLA,
       A.NOME,
       A.ENDERECO,
       A.COMPLEMENTO,
       A.CEP,
       A.CIDADE,
       A.BAIRRO,
       A.UF,
       A.ID_TIPO_LOCAL,
       B.DESC_ALOCACAO,
       A.ID_RESPONSAVEL,
       C.NOME AS RESPONSAVEL,
       C.APELIDO,
	  A.CODIGO, 
	  A.TELEFONE,
	  A.CELULAR, 
	  A.ID_AREA,
	  D.DESC_AREA,
	  A.LOJA_FISICA,
	  A.PARCERIA,
	  D.ID_RESPONSAVEL AS ID_RESPONSAVEL_AREA,
	  E.NOME AS RESPONSAVEL_AREA,
	  A.ID_EMPRESA,
	  A.ID_TIPO_LOCAL_ESTOQUE,
	  A.TELEFONE2,
	  A.CELULAR2,
	  A.CELULAR3,
	  A.CELULAR4,
	  A.CELULAR5,
	  A.CELULAR6,
	  A.INATIVO,
	  A.ULTIMA_ATUALIZACAO,
	  A.INICIO_VIGENCIA,
	  A.FINAL_VIGENCIA

FROM 
	CG_LOJA_HISTORICO AS A (NOLOCK)
LEFT JOIN 
	dbo.CG_ALOCACAO AS B (NOLOCK)
		ON A.ID_TIPO_LOCAL = B.ID_ALOCACAO
LEFT JOIN 
	dbo.CG_RESPONSAVEL AS C (NOLOCK)
		ON A.ID_RESPONSAVEL = C.ID_RESPONSAVEL AND A.ID_EMPRESA = C.ID_EMPRESA
LEFT JOIN 
    dbo.CG_AREA AS D (NOLOCK)
		ON D.ID_AREA = A.ID_AREA AND D.ID_EMPRESA = A.ID_EMPRESA
LEFT JOIN 
	dbo.CG_RESPONSAVEL AS E (NOLOCK)
		ON D.ID_RESPONSAVEL = E.ID_RESPONSAVEL AND D.ID_EMPRESA = E.ID_EMPRESA









GO


