CREATE TABLE CG_TABELA_SERVICOS_FORNECEDOR (
ID_FORNECEDOR INT NOT NULL,
ID_TABELA VARCHAR(10) NOT NULL,
PRECO NUMERIC(12,2) NOT NULL,
ID_ITEM UNIQUEIDENTIFIER NOT NULL,
CONSTRAINT PK_CG_TABELA_SERVICOS_FORNECEDOR PRIMARY KEY (ID_ITEM),
CONSTRAINT UNQ_CG_TABELA_SERVICOS_FORNECEDOR UNIQUE (ID_FORNECEDOR, ID_TABELA) 
)
GO