CREATE TABLE CG_TABELA_SERVICOS_FORNECEDOR_ITEM (
ID_ITEM UNIQUEIDENTIFIER NOT NULL,
ID_FORNECEDOR INT NOT NULL,
ID_CONCERTO INT NOT NULL,
ID INT IDENTITY(1,1) NOT NULL,
CONSTRAINT PK_CG_TABELA_SERVICOS_FORNECEDOR_ITEM PRIMARY KEY (ID),
CONSTRAINT UNQ_CG_TABELA_SERVICOS_FORNECEDOR_ITEM UNIQUE (ID_FORNECEDOR, ID_CONCERTO) 
)
GO