CREATE VIEW VW_CG_TABELA_SERVICOS_FORNECEDOR_ITEM 
AS 
SELECT 
A.ID,
A.ID_CONCERTO, 
C.DESC_CONCERTO,
B.ID_TABELA,
B.PRECO,
A.ID_FORNECEDOR, 
F.NOME, 
F.SIGLA,
CAST(A.ID_ITEM AS VARCHAR(50)) AS ID_ITEM
FROM CG_TABELA_SERVICOS_FORNECEDOR_ITEM A
INNER JOIN CG_TABELA_SERVICOS_FORNECEDOR B ON B.ID_ITEM = A.ID_ITEM
LEFT JOIN CG_FORNECEDOR F ON F.ID_FORNECEDOR = A.ID_FORNECEDOR
LEFT JOIN CG_CONCERTO C ON C.ID_CONCERTO = A.ID_CONCERTO
GO

