USE [dbCG]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CG_MOVIMENTO_CHIP_INATIVO_ITEM](
	[ID_ROMANEIO] [int] NOT NULL,
	[UNIQUE_KEYID] [uniqueidentifier] NOT NULL,
	[ID_CHIP] [int] NOT NULL,
	[SIMID] [varchar](20) NOT NULL,
	[QTD] [int] NOT NULL,
	[VALOR] [numeric](12, 2) NULL,
	[TRANSITO] [bit] NOT NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[ID_ROMANEIO] ASC,
	[UNIQUE_KEYID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CG_MOVIMENTO_CHIP_INATIVO_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_CG_MOVIMENTO_CHIP_INATIVO_ITEM_1] FOREIGN KEY([ID_ROMANEIO])
REFERENCES [dbo].[CG_MOVIMENTO_CHIP_INATIVO] ([ID_ROMANEIO])
GO

ALTER TABLE [dbo].[CG_MOVIMENTO_CHIP_INATIVO_ITEM] CHECK CONSTRAINT [FK_CG_MOVIMENTO_CHIP_INATIVO_ITEM_1]
GO

ALTER TABLE [dbo].[CG_MOVIMENTO_CHIP_INATIVO_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_CG_MOVIMENTO_CHIP_INATIVO_ITEM_2] FOREIGN KEY([ID_CHIP])
REFERENCES [dbo].[CG_CHIP] ([ID_CHIP])
GO

ALTER TABLE [dbo].[CG_MOVIMENTO_CHIP_INATIVO_ITEM] CHECK CONSTRAINT [FK_CG_MOVIMENTO_CHIP_INATIVO_ITEM_2]
GO

