USE [dbCG]
GO

/****** Object:  Table [dbo].[CG_LOJA_HISTORICO]    Script Date: 26/05/2018 17:07:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CG_LOJA_HISTORICO](
	[ID_HISTORICO] INT NOT NULL IDENTITY(1,1),
	[ID_LOJA] [int] NOT NULL,
	[SIGLA] [varchar](50) NULL,
	[NOME] [varchar](50) NULL,
	[ENDERECO] [varchar](70) NULL,
	[COMPLEMENTO] [varchar](40) NULL,
	[CEP] [varchar](9) NULL,
	[CIDADE] [varchar](50) NULL,
	[BAIRRO] [varchar](50) NULL,
	[UF] [char](2) NULL,
	[ID_TIPO_LOCAL] [int] NULL,
	[ID_RESPONSAVEL] [int] NULL,
	[USER_INS] [int] NULL,
	[DATA_INS] [datetime] NULL,
	[USER_UPD] [int] NULL,
	[DATA_UPD] [datetime] NULL,
	[CODIGO] [varchar](10) NOT NULL,
	[TELEFONE] [varchar](20) NULL,
	[CELULAR] [varchar](20) NULL,
	[LOJA_FISICA] [bit] NOT NULL DEFAULT ((0)),
	[PARCERIA] [bit] NOT NULL DEFAULT ((0)),
	[ID_AREA] [char](8) NOT NULL CONSTRAINT [DF_CG_LOJA_HISTORICO_ID_AREA]  DEFAULT ('0'),
	[ID_EMPRESA] [int] NOT NULL,
	[ID_TIPO_LOCAL_ESTOQUE] [int] NOT NULL DEFAULT ((10)),
	[TELEFONE2] [varchar](20) NULL,
	[CELULAR2] [varchar](20) NULL,
	[CELULAR3] [varchar](20) NULL,
	[CELULAR4] [varchar](20) NULL,
	[CELULAR5] [varchar](20) NULL,
	[CELULAR6] [varchar](20) NULL,
	[INATIVO] [bit] NOT NULL CONSTRAINT [DF_INATIVO_CG_LOJA_HISTORICO]  DEFAULT ((0)),
	[ULTIMA_ATUALIZACAO] [datetime] NOT NULL CONSTRAINT [DF_ULT_ATUALIZACAO_CG_LOJA_HISTORICO]  DEFAULT (getdate()),
	[INICIO_VIGENCIA] [datetime] NULL,
	[FINAL_VIGENCIA] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_HISTORICO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_CG_LOJA_HISTORICO_CODIGO] UNIQUE NONCLUSTERED 
(
	[ID_EMPRESA] ASC,
	[CODIGO] ASC,
	[ID_HISTORICO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CG_LOJA_HISTORICO]  WITH CHECK ADD  CONSTRAINT [FK_CG_LOJA_HISTORICO_1] FOREIGN KEY([ID_TIPO_LOCAL])
REFERENCES [dbo].[CG_ALOCACAO] ([ID_ALOCACAO])
GO

ALTER TABLE [dbo].[CG_LOJA_HISTORICO] CHECK CONSTRAINT [FK_CG_LOJA_HISTORICO_1]
GO

ALTER TABLE [dbo].[CG_LOJA_HISTORICO]  WITH CHECK ADD  CONSTRAINT [FK_CG_LOJA_HISTORICO_2] FOREIGN KEY([ID_RESPONSAVEL])
REFERENCES [dbo].[CG_RESPONSAVEL] ([ID_RESPONSAVEL])
GO

ALTER TABLE [dbo].[CG_LOJA_HISTORICO] CHECK CONSTRAINT [FK_CG_LOJA_HISTORICO_2]
GO

ALTER TABLE [dbo].[CG_LOJA_HISTORICO]  WITH CHECK ADD  CONSTRAINT [FK_CG_LOJA_HISTORICO_CG_AREA_01] FOREIGN KEY([ID_AREA], [ID_EMPRESA])
REFERENCES [dbo].[CG_AREA] ([ID_AREA], [ID_EMPRESA])
GO

ALTER TABLE [dbo].[CG_LOJA_HISTORICO] CHECK CONSTRAINT [FK_CG_LOJA_HISTORICO_CG_AREA_01]
GO

ALTER TABLE [dbo].[CG_LOJA_HISTORICO]  WITH CHECK ADD  CONSTRAINT [FK_CG_TIPO_LOCAL_ESTOQUE_01_HISTORICO] FOREIGN KEY([ID_TIPO_LOCAL_ESTOQUE])
REFERENCES [dbo].[CG_TIPO_LOCAL_ESTOQUE] ([ID_TIPO_LOCAL_ESTOQUE])
GO

ALTER TABLE [dbo].[CG_LOJA_HISTORICO] CHECK CONSTRAINT [FK_CG_TIPO_LOCAL_ESTOQUE_01_HISTORICO]
GO


