CREATE PROCEDURE spDel_Cg_equipamento_vs_chip

	@ID_EQUIPAMENTO As int,
	@ID_CHIP As int

AS

BEGIN
DELETE FROM CG_EQUIPAMENTO_VS_CHIP WHERE
	ID_EQUIPAMENTO = @ID_EQUIPAMENTO AND
	ID_CHIP = @ID_CHIP

END