CREATE INDEX IX_CG_ESTOQUE_EQUIPAMENTO_DATAMOV ON CG_ESTOQUE_EQUIPAMENTO (DATAMOV)
GO
CREATE INDEX IX_CG_ESTOQUE_CHIP_DATAMOV ON CG_ESTOQUE_CHIP (DATAMOV)
GO
CREATE INDEX IX_CG_EQUIPAMENTO_SERIE ON CG_EQUIPAMENTO (SERIE)
GO
CREATE INDEX IX_CG_CHIP_SIMID ON CG_CHIP (SIMID)
GO