DELETE FROM CG_TRANSITO WHERE ID_EMPRESA <> 1
GO

ALTER TABLE CG_TRANSITO 
DROP COLUMN ID_EMPRESA
GO

--DELETE FROM CG_TRANSITO WHERE CONTROLE_INTERNO=1 AND ID_TRANSITO>1

--DELETE FROM CG_TRANSITO WHERE ID_TRANSITO IN (24,27,26, 28)