USE [dbCG]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[TGR_LOJA] ON [dbo].[CG_LOJA] 
FOR INSERT, UPDATE
AS
BEGIN

DECLARE @ERRO BIT, @MSG VARCHAR(100)
SET @ERRO = 0
SET @MSG = ''

DECLARE @TELEFONE VARCHAR(20), @CELULAR VARCHAR(20), @VALCNT TINYINT

SELECT @TELEFONE = i.TELEFONE, @CELULAR = i.CELULAR
FROM INSERTED i

SET @VALCNT = 0
IF RTRIM(LTRIM(ISNULL(@TELEFONE,''))) <> ''
BEGIN
    SET @VALCNT = @VALCNT + 1
END

IF RTRIM(LTRIM(ISNULL(@CELULAR,''))) <> ''
BEGIN
    SET @VALCNT = @VALCNT + 1
END

IF @VALCNT = 0
BEGIN
    SET @ERRO = 1
    SET @MSG = 'É OBRIGATÓRIO PREENCHIMENTO DO TELEFONE FIXO OU CELULAR DA LOJA!!!' 
END

IF @ERRO = 1
BEGIN
    RAISERROR(@MSG, 16, 1)
END
ELSE
BEGIN
    RETURN
END

END
