INSERT INTO CG_PARAMETRO_PESQUISA_DINAMICA 
  (TABELA, COLUNA, IDCOLUNA, ORDERCOL, CHAVE, TIPODADO, COLUNA_FILTRO, APELIDO_COLUNA, MOSTRA_COLUNA)
  VALUES
  ('VW_CG_LOJA', 'TELEFONE', 17, 17, 0, 'String', 1, 'telefone', 1),
  ('VW_CG_LOJA', 'CELULAR', 18, 18, 0, 'String', 1, 'celular', 1)
