
ALTER TABLE CG_EQUIPAMENTO
ADD ID_CONTROLE AS 'SR' + RIGHT('00000'+ CONVERT(VARCHAR, CG_EQUIPAMENTO.ID_EQUIPAMENTO), 5)  
GO

CREATE UNIQUE INDEX IDX_CG_EQUIPAMENTO_ID_CONTROLE ON CG_EQUIPAMENTO (ID_CONTROLE ASC)
GO



