INSERT INTO CG_PARAMETRO_PESQUISA_DINAMICA 
  (TABELA, COLUNA, IDCOLUNA, ORDERCOL, CHAVE, TIPODADO, COLUNA_FILTRO, APELIDO_COLUNA, MOSTRA_COLUNA)
  VALUES
  ('VW_CG_EQUIPAMENTO', 'NF_ENTRADA', 14, 14, 0, 'String', 1, 'nf_entrada', 1),
  ('VW_CG_EQUIPAMENTO', 'DATA_NF', 15, 15, 0, 'Date', 1, 'data_nf', 1),
  ('VW_CG_EQUIPAMENTO', 'PRAZO_GARANTIA', 16, 16, 0, 'Integer', 1, 'prazo_garantia', 1),
  ('VW_CG_EQUIPAMENTO', 'ID_CONTROLE', 17, 17, 0, 'String', 1, 'id_controle', 1)


  