USE [dbCG]
GO

/****** Object:  Table [dbo].[CG_ENTRADA_CHIP_ITEM]    Script Date: 20/10/2019 17:56:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CG_LOG_ENTRADA_CHIP_ITEM](
	[ID_ROMANEIO] [int] NOT NULL,
	[UNIQUE_KEYID] [uniqueidentifier] NOT NULL,
	[ID_CHIP] [int] NOT NULL,
	[SIMID] [varchar](20) NOT NULL,
	[QTD] [int] NOT NULL,
	[VALOR] [numeric](12, 2) NULL,
	[ID_EMPRESA] [int] NOT NULL,
	[ID_EMPRESA_OLD] [int] NULL,
	[DT_ALT_EMPRESA_OLD] [datetime] NULL,
	[MOVIMENTO_CONFERIDO] [BIT] NOT NULL,
	[REPROVADO] [BIT] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ROMANEIO] ASC,
	[UNIQUE_KEYID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CG_LOG_ENTRADA_CHIP_ITEM] ADD  CONSTRAINT [DF_CG_LOG_ENTRADA_CHIP_ITEM_MOVIMENTO_CONFERIDO]  DEFAULT (0) FOR [MOVIMENTO_CONFERIDO]
GO

ALTER TABLE [dbo].[CG_LOG_ENTRADA_CHIP_ITEM] ADD  CONSTRAINT [DF_CG_LOG_ENTRADA_CHIP_ITEM_REPROVADO]  DEFAULT (0) FOR [REPROVADO]
GO

ALTER TABLE [dbo].[CG_LOG_ENTRADA_CHIP_ITEM] ADD  CONSTRAINT [DF_CG_LOG_ENTRADA_CHIP_ITEM_DT_ALT_EMPRESA_OLD]  DEFAULT (getdate()) FOR [DT_ALT_EMPRESA_OLD]
GO

ALTER TABLE [dbo].[CG_LOG_ENTRADA_CHIP_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_CG_LOG_ENTRADA_CHIP_ITEM_2] FOREIGN KEY([ID_CHIP])
REFERENCES [dbo].[CG_CHIP] ([ID_CHIP])
GO

ALTER TABLE [dbo].[CG_LOG_ENTRADA_CHIP_ITEM] CHECK CONSTRAINT [FK_CG_LOG_ENTRADA_CHIP_ITEM_2]
GO


