USE [dbCG]
GO

/****** Object:  Table [dbo].[CG_LOG_ENTRADA_EQUIPAMENTO_ITEM]    Script Date: 20/10/2019 18:06:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CG_LOG_ENTRADA_EQUIPAMENTO_ITEM](
	[ID_ROMANEIO] [int] NOT NULL,
	[UNIQUE_KEYID] [uniqueidentifier] NOT NULL,
	[ID_EQUIPAMENTO] [int] NOT NULL,
	[SERIE] [varchar](30) NOT NULL,
	[QTD] [int] NOT NULL,
	[VALOR] [numeric](12, 2) NULL,
	[ID_EMPRESA] [int] NOT NULL,
	[ID_EMPRESA_OLD] [int] NULL,
	[DT_ALT_EMPRESA_OLD] [datetime] NULL,
	[MOVIMENTO_CONFERIDO] [BIT] NOT NULL,
	[REPROVADO] [BIT] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ROMANEIO] ASC,
	[UNIQUE_KEYID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CG_LOG_ENTRADA_EQUIPAMENTO_ITEM] ADD  CONSTRAINT [DF_CG_LOG_ENTRADA_EQUIPAMENTO_ITEM_MOVIMENTO_CONFERIDO]  DEFAULT (0) FOR [MOVIMENTO_CONFERIDO]
GO

ALTER TABLE [dbo].[CG_LOG_ENTRADA_EQUIPAMENTO_ITEM] ADD  CONSTRAINT [DF_CG_LOG_ENTRADA_EQUIPAMENTO_ITEM_REPROVADO]  DEFAULT (0) FOR [REPROVADO]
GO

ALTER TABLE [dbo].[CG_LOG_ENTRADA_EQUIPAMENTO_ITEM] ADD  CONSTRAINT [DF_CG_LOG_ENTRADA_EQUIPAMENTO_ITEM_DT_ALT_EMPRESA_OLD]  DEFAULT (getdate()) FOR [DT_ALT_EMPRESA_OLD]
GO

ALTER TABLE [dbo].[CG_LOG_ENTRADA_EQUIPAMENTO_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_CG_LOG_ENTRADA_EQUIPAMENTO_ITEM_2] FOREIGN KEY([ID_EQUIPAMENTO])
REFERENCES [dbo].[CG_EQUIPAMENTO] ([ID_EQUIPAMENTO])
GO

ALTER TABLE [dbo].[CG_LOG_ENTRADA_EQUIPAMENTO_ITEM] CHECK CONSTRAINT [FK_CG_LOG_ENTRADA_EQUIPAMENTO_ITEM_2]
GO


