
USE [dbCG]
GO

ALTER TABLE CG_FORNECEDOR
ADD GARANTIA_AQUISICAO INT NULL, GARANTIA_ASSISTENCIA INT NULL
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_CG_FORNECEDOR]
AS
SELECT A.ID_FORNECEDOR,
       A.SIGLA,
       A.UTILIZA_NFTS,
       A.NOME,
       A.CEP,
       A.ENDERECO,
       A.COMPLEMENTO,
       A.CIDADE,
       A.BAIRRO,
       A.UF,
       A.EMAIL,
       A.TELEFONE,
       A.CONTATO,
       A.WHATSAPP,
       A.ID_TIPO_SERVICO,
       A.OBS,
       B.DESC_TIPO_SERVICO,
	  A.GARANTIA_AQUISICAO,
	  A.GARANTIA_ASSISTENCIA
FROM 
	CG_FORNECEDOR AS A (NOLOCK)
LEFT JOIN 
	CG_TIPO_SERVICO AS B (NOLOCK)
		ON A.ID_TIPO_SERVICO = B.ID_TIPO_SERVICO
GO

