INSERT INTO CG_PARAMETRO_PESQUISA_DINAMICA 
  (TABELA, COLUNA, IDCOLUNA, ORDERCOL, CHAVE, TIPODADO, COLUNA_FILTRO, APELIDO_COLUNA, MOSTRA_COLUNA)
  VALUES
  ('VW_CG_FORNECEDOR', 'GARANTIA_AQUISICAO', 18, 18, 0, 'Integer', 1, 'Garantia_Aquisicao', 1),
  ('VW_CG_FORNECEDOR', 'GARANTIA_ASSISTENCIA', 19, 19, 0, 'Integer', 1, 'Garantia_Assistencia', 1)
 

