UPDATE CG_SEQUENCIAL 
SET KEYID = 43
WHERE TABELA = 'CG_MODULO'
GO

insert into CG_MODULO (ID_MODULO, DESC_MODULO, USER_INS, DATA_INS, USER_UPD, DATA_UPD)
VALUES (43, 'MOVIMENTAR CHIP P/ ESTOQUE INATIVO', 1, GETDATE(), 1, GETDATE())
GO

UPDATE CG_SEQUENCIAL 
SET KEYID = 44
WHERE TABELA = 'CG_MODULO'
GO

insert into CG_MODULO (ID_MODULO, DESC_MODULO, USER_INS, DATA_INS, USER_UPD, DATA_UPD)
VALUES (44, 'MOVIMENTAR EQUIPAMENTO P/ ESTOQUE INATIVO', 1, GETDATE(), 1, GETDATE())
GO