USE [dbCG]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_CG_MOVIMENTO_CHIP_INATIVO_ITEM] 
AS
SELECT A.ID_ROMANEIO,
       A.UNIQUE_KEYID,
       A.ID_CHIP,
       B.SIMID,
	   B.ID_OPERADORA,
	   C.DESC_OPERADORA,
       A.QTD,
       A.VALOR, 
	  A.TRANSITO
FROM 
	CG_MOVIMENTO_CHIP_INATIVO_ITEM AS A (NOLOCK)
LEFT JOIN 
	CG_CHIP AS B (NOLOCK)
		ON A.ID_CHIP = B.ID_CHIP
LEFT JOIN 
	CG_OPERADORA AS C (NOLOCK)
		ON B.ID_OPERADORA = C.ID_OPERADORA
GO


