USE [dbCG]
GO

/****** Object:  Table [dbo].[CG_MOVIMENTO_EQUIPAMENTO_INATIVO]    Script Date: 20/05/2017 14:05:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CG_MOVIMENTO_EQUIPAMENTO_INATIVO](
	[ID_ROMANEIO] [int] NOT NULL,
	[DATA_MOVTO] [datetime] NOT NULL,
	[ID_RESPONSAVEL] [int] NOT NULL,
	[ID_LOJA_ORIGEM] [int] NOT NULL,
	[ID_LOJA_DESTINO] [int] NOT NULL,
	[TIPO_OP] [char](1) NOT NULL,
	[USER_INS] [int] NULL,
	[DATA_INS] [datetime] NULL,
	[USER_UPD] [int] NULL,
	[DATA_UPD] [datetime] NULL,
	[QTD_TOTAL] [int] NULL,
	[QTD_RECEBIDA] [int] NULL,
	[ROMANEIO_ESTOQUE] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ROMANEIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CG_MOVIMENTO_EQUIPAMENTO_INATIVO]  WITH CHECK ADD  CONSTRAINT [FK_CG_MOVIMENTO_EQUIPAMENTO_INATIVO_1] FOREIGN KEY([ID_RESPONSAVEL])
REFERENCES [dbo].[CG_RESPONSAVEL] ([ID_RESPONSAVEL])
GO

ALTER TABLE [dbo].[CG_MOVIMENTO_EQUIPAMENTO_INATIVO] CHECK CONSTRAINT [FK_CG_MOVIMENTO_EQUIPAMENTO_INATIVO_1]
GO

ALTER TABLE [dbo].[CG_MOVIMENTO_EQUIPAMENTO_INATIVO]  WITH CHECK ADD  CONSTRAINT [FK_CG_MOVIMENTO_EQUIPAMENTO_INATIVO_2] FOREIGN KEY([ID_LOJA_ORIGEM])
REFERENCES [dbo].[CG_LOJA] ([ID_LOJA])
GO

ALTER TABLE [dbo].[CG_MOVIMENTO_EQUIPAMENTO_INATIVO] CHECK CONSTRAINT [FK_CG_MOVIMENTO_EQUIPAMENTO_INATIVO_2]
GO

ALTER TABLE [dbo].[CG_MOVIMENTO_EQUIPAMENTO_INATIVO]  WITH CHECK ADD  CONSTRAINT [FK_CG_MOVIMENTO_EQUIPAMENTO_INATIVO_3] FOREIGN KEY([ID_LOJA_DESTINO])
REFERENCES [dbo].[CG_LOJA] ([ID_LOJA])
GO

ALTER TABLE [dbo].[CG_MOVIMENTO_EQUIPAMENTO_INATIVO] CHECK CONSTRAINT [FK_CG_MOVIMENTO_EQUIPAMENTO_INATIVO_3]
GO


