USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_MOVIMENTO_EQUIPAMENTO_INATIVO]    Script Date: 20/05/2017 14:14:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_CG_MOVIMENTO_EQUIPAMENTO_INATIVO]
AS
SELECT A.ID_ROMANEIO,
       A.DATA_MOVTO,
       A.ID_RESPONSAVEL,
       B.NOME AS RESPONSAVEL,
       B.APELIDO,
       A.ID_LOJA_ORIGEM,
       C.SIGLA AS SIGLA_ORIGEM,
       C.NOME AS NOME_ORIGEM,
       A.ID_LOJA_DESTINO,
       D.SIGLA AS SIGLA_DESTINO,
       D.NOME AS NOME_DESTINO,
       A.TIPO_OP,
	  A.QTD_RECEBIDA,
	  A.QTD_TOTAL
FROM 
	CG_MOVIMENTO_EQUIPAMENTO_INATIVO AS A
LEFT JOIN 
	CG_RESPONSAVEL AS B 
		ON A.ID_RESPONSAVEL = B.ID_RESPONSAVEL
LEFT JOIN 
	CG_LOJA AS C ON A.ID_LOJA_ORIGEM = C.ID_LOJA
LEFT JOIN 
	CG_LOJA AS D 
		ON A.ID_LOJA_DESTINO = D.ID_LOJA

GO


