INSERT INTO CG_PARAMETRO_PESQUISA_DINAMICA 
  (TABELA, COLUNA, IDCOLUNA, ORDERCOL, CHAVE, TIPODADO, COLUNA_FILTRO, APELIDO_COLUNA, MOSTRA_COLUNA)
  SELECT 
    'VW_CG_MOVIMENTO_EQUIPAMENTO_INATIVO' AS TABELA, 
    COLUNA, 
    IDCOLUNA, 
    ORDERCOL, 
    CHAVE, 
    TIPODADO, 
    COLUNA_FILTRO, 
    APELIDO_COLUNA, 
    MOSTRA_COLUNA 
 FROM CG_PARAMETRO_PESQUISA_DINAMICA
 WHERE TABELA = 'VW_CG_MOVIMENTO_EQUIPAMENTO'

