CREATE VIEW VW_CG_ORIGEM_ESTOQUE_POS
AS
SELECT
	CT.DESC_TIPO_LOCAL_ESTOQUE AS ORIGEM,
    A.ID_EQUIPAMENTO, 
    B.SERIE, 
    B.MODELO, 
    B.DESC_EQUIPAMENTO, 
	A.ID_EMPRESA,
	L.ID_TIPO_LOCAL_ESTOQUE
    
FROM
    dbo.CG_ESTOQUE_EQUIPAMENTO AS A 
	   INNER JOIN
		  dbo.CG_EQUIPAMENTO AS B 
			 ON A.ID_EQUIPAMENTO = B.ID_EQUIPAMENTO
		LEFT JOIN CG_LOJA L
				ON L.ID_LOJA = A.ID_LOCAL 
		LEFT JOIN 
			CG_TIPO_LOCAL_ESTOQUE CT ON CT.ID_TIPO_LOCAL_ESTOQUE = L.ID_TIPO_LOCAL_ESTOQUE
WHERE A.TRANSITO = 0 AND L.ID_TIPO_LOCAL_ESTOQUE NOT IN (0, 2, 7, 9, 10)




