USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_OS_ITEM]    Script Date: 23/09/2018 10:00:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[VW_CG_OS_ITEM]
AS
SELECT A.ID_OS,
       A.ITEM_ID,
       A.ID_EQUIPAMENTO,
       B.ID_TIPO_EQUIPAMENTO,
       D.DESC_TIPO_EQUIPAMENTO,
       B.DESC_EQUIPAMENTO,
       B.SERIE,
       B.MODELO,
       B.ID_FORNECEDOR,
       E.SIGLA AS SIGLA_FORNECEDOR,
       E.UTILIZA_NFTS,
       E.NOME AS NOME_FORNECEDOR,
       B.PROTOCOLO,
       A.PREVISAO_RETORNO,
       A.DATA_RETORNO,
       A.DESC_DEFEITO,
       A.CONSERTO_OK,
       A.NF_FORNEC,
       A.SERIE_NF_FORNEC,
       A.EMISSAO_NF_FORNEC,
	  A.OBS_RETORNO,
       A.ID_RESPONSAVEL_RET,
       C.NOME AS RESPONSAVEL,
       C.APELIDO AS APELIDO_RESPONSAVEL,
       A.XML_NF_FORNEC,
       A.LAUDO_FORNEC,
	  A.GARANTIA,
	  A.RECEBIDO,
	  A.VALOR_CONSERTO,
	  A.CONFIG_GARANTIA, 
	  ISNULL(A.QTDE_DIAS_GARANTIA,0) AS QTDE_DIAS_GARANTIA,
	  A.DATA_INICIO_GARANTIA, 
	  A.DATA_TERMINO_GARANTIA,
	  ISNULL(OC.ID_OCORRENCIA,0) AS ID_OCORRENCIA,
	  ISNULL(OC.DESCRICAO,'-') AS DESC_OCORRENCIA,
	  A.LAUDO,
	  A.OUTROS,
	  A.MOTIVO_OUTROS,
	  A.ID_TABELA
FROM 
	CG_OS_ITEM AS A (NOLOCK)
LEFT JOIN 
	CG_EQUIPAMENTO AS B (NOLOCK)
		ON A.ID_EQUIPAMENTO = B.ID_EQUIPAMENTO
LEFT JOIN 
	CG_RESPONSAVEL AS C (NOLOCK)
		ON A.ID_RESPONSAVEL_RET = C.ID_RESPONSAVEL
LEFT JOIN 
	CG_TIPO_EQUIPAMENTO AS D (NOLOCK)
		ON B.ID_TIPO_EQUIPAMENTO = D.ID_TIPO_EQUIPAMENTO
LEFT JOIN 
	CG_FORNECEDOR AS E (NOLOCK)
		ON B.ID_FORNECEDOR = E.ID_FORNECEDOR
LEFT JOIN ( 
        SELECT	DESCRICAO, 
        DBO.FNCSPLIT(ISNULL(OS_VINCULADA,''),'|',1) AS ID_OS1, 
        DBO.FNCSPLIT(ISNULL(OS_VINCULADA,''),'|',2) AS ITEM_ID, 
        DBO.FNCSPLIT(ISNULL(OS_VINCULADA,''),'|',3) AS ID_EQUIPAMENTO,
		ID_OCORRENCIA 
        FROM CG_OCORRENCIA) AS OC 
			ON OC.ID_OS1 = A.ID_OS AND OC.ITEM_ID = A.ITEM_ID 
				 AND OC.ID_EQUIPAMENTO = A.ID_EQUIPAMENTO 




GO


