USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_OS_ITEM]    Script Date: 03/06/2017 08:37:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_CG_OS_ITEM]
AS
SELECT A.ID_OS,
       A.ITEM_ID,
       A.ID_EQUIPAMENTO,
       B.ID_TIPO_EQUIPAMENTO,
       D.DESC_TIPO_EQUIPAMENTO,
       B.DESC_EQUIPAMENTO,
       B.SERIE,
       B.MODELO,
       B.ID_FORNECEDOR,
       E.SIGLA AS SIGLA_FORNECEDOR,
       E.UTILIZA_NFTS,
       E.NOME AS NOME_FORNECEDOR,
       B.PROTOCOLO,
       A.PREVISAO_RETORNO,
       A.DATA_RETORNO,
       A.DESC_DEFEITO,
       A.CONSERTO_OK,
       A.NF_FORNEC,
       A.SERIE_NF_FORNEC,
       A.EMISSAO_NF_FORNEC,
	  A.OBS_RETORNO,
       A.ID_RESPONSAVEL_RET,
       C.NOME AS RESPONSAVEL,
       C.APELIDO AS APELIDO_RESPONSAVEL,
       A.XML_NF_FORNEC,
       A.LAUDO_FORNEC,
	  A.GARANTIA,
	  A.RECEBIDO,
	  A.VALOR_CONSERTO
FROM 
	CG_OS_ITEM AS A (NOLOCK)
LEFT JOIN 
	CG_EQUIPAMENTO AS B (NOLOCK)
		ON A.ID_EQUIPAMENTO = B.ID_EQUIPAMENTO
LEFT JOIN 
	CG_RESPONSAVEL AS C (NOLOCK)
		ON A.ID_RESPONSAVEL_RET = C.ID_RESPONSAVEL
LEFT JOIN 
	CG_TIPO_EQUIPAMENTO AS D (NOLOCK)
		ON B.ID_TIPO_EQUIPAMENTO = D.ID_TIPO_EQUIPAMENTO
LEFT JOIN 
	CG_FORNECEDOR AS E (NOLOCK)
		ON B.ID_FORNECEDOR = E.ID_FORNECEDOR
GO


