

INSERT INTO CG_PARAMETRO_PESQUISA_DINAMICA
(TABELA, COLUNA, IDCOLUNA, ORDERCOL, CHAVE, TIPODADO, COLUNA_FILTRO, APELIDO_COLUNA, MOSTRA_COLUNA)
VALUES
('VW_CG_EQUIPAMENTO', 'ID_ULTIMA_OS', 18, 18, 0, 'Integer', 1, 'id_ultima_os', 1),
('VW_CG_EQUIPAMENTO', 'DATA_INICIO_GARANTIA', 19, 19, 0, 'Date', 1, 'data_inicio_garantia', 1),
('VW_CG_EQUIPAMENTO', 'DATA_TERMINO_GARANTIA', 20, 20, 0, 'Date', 1, 'data_termino_garantia', 1)

