ALTER TABLE CG_OS_ITEM
	ADD CONSTRAINT FK_CG_OS_ITEM_1
	FOREIGN KEY (ID_OS)
	REFERENCES CG_OS(ID_OS)
GO

ALTER TABLE CG_OS_ITEM
	ADD CONSTRAINT FK_CG_OS_ITEM_2
	FOREIGN KEY (ID_EQUIPAMENTO)
	REFERENCES CG_EQUIPAMENTO(ID_EQUIPAMENTO)
GO

ALTER TABLE CG_OS_ITEM
	ADD CONSTRAINT FK_CG_OS_ITEM_3
	FOREIGN KEY (ID_RESPONSAVEL_RET)
	REFERENCES CG_RESPONSAVEL(ID_RESPONSAVEL)
GO

