ALTER TABLE CG_LOJA
	ADD CONSTRAINT FK_CG_LOJA_1
	FOREIGN KEY (ID_TIPO_LOCAL)
	REFERENCES CG_ALOCACAO(ID_ALOCACAO)
GO

ALTER TABLE CG_LOJA
	ADD CONSTRAINT FK_CG_LOJA_2
	FOREIGN KEY (ID_RESPONSAVEL)
	REFERENCES CG_RESPONSAVEL(ID_RESPONSAVEL)
GO