ALTER TABLE CG_OS
	ADD CONSTRAINT FK_CG_OS_1
	FOREIGN KEY (ID_LOJA_ORIGEM)
	REFERENCES CG_LOJA(ID_LOJA)
GO

ALTER TABLE CG_OS
	ADD CONSTRAINT FK_CG_OS_2
	FOREIGN KEY (ID_FORNECEDOR)
	REFERENCES CG_FORNECEDOR(ID_FORNECEDOR)
GO

ALTER TABLE CG_OS
	ADD CONSTRAINT FK_CG_OS_3
	FOREIGN KEY (ID_RESPONSAVEL_IDA)
	REFERENCES CG_RESPONSAVEL(ID_RESPONSAVEL)
GO

ALTER TABLE CG_OS
	ADD CONSTRAINT FK_CG_OS_4
	FOREIGN KEY (STATUS_OS)
	REFERENCES CG_STATUS_OS(ID_STATUS)
GO