ALTER TABLE CG_MOVIMENTO_CHIP_ITEM
	ADD CONSTRAINT FK_CG_MOVIMENTO_CHIP_ITEM_1
	FOREIGN KEY (ID_ROMANEIO)
	REFERENCES CG_MOVIMENTO_CHIP(ID_ROMANEIO)
GO

ALTER TABLE CG_MOVIMENTO_CHIP_ITEM
	ADD CONSTRAINT FK_CG_MOVIMENTO_CHIP_ITEM_2
	FOREIGN KEY (ID_CHIP)
	REFERENCES CG_CHIP(ID_CHIP)
GO

