ALTER TABLE CG_MOVIMENTO_CHIP
	ADD CONSTRAINT FK_CG_MOVIMENTO_CHIP_1
	FOREIGN KEY (ID_RESPONSAVEL)
	REFERENCES CG_RESPONSAVEL(ID_RESPONSAVEL)
GO

ALTER TABLE CG_MOVIMENTO_CHIP
	ADD CONSTRAINT FK_CG_MOVIMENTO_CHIP_2
	FOREIGN KEY (ID_LOJA_ORIGEM)
	REFERENCES CG_LOJA(ID_LOJA)
GO

ALTER TABLE CG_MOVIMENTO_CHIP
	ADD CONSTRAINT FK_CG_MOVIMENTO_CHIP_3
	FOREIGN KEY (ID_LOJA_DESTINO)
	REFERENCES CG_LOJA(ID_LOJA)
GO