
ALTER TABLE CG_ENTRADA_EQUIPAMENTO_ITEM
	ADD CONSTRAINT FK_CG_ENTRADA_EQUIPAMENTO_ITEM_1
	FOREIGN KEY (ID_ROMANEIO)
	REFERENCES CG_ENTRADA_EQUIPAMENTO(ID_ROMANEIO)
GO

ALTER TABLE CG_ENTRADA_EQUIPAMENTO_ITEM
	ADD CONSTRAINT FK_CG_ENTRADA_EQUIPAMENTO_ITEM_2
	FOREIGN KEY (ID_EQUIPAMENTO)
	REFERENCES CG_EQUIPAMENTO(ID_EQUIPAMENTO)
GO
