ALTER TABLE CG_EQUIPAMENTO
	ADD CONSTRAINT FK_CG_EQUIPAMENTO_1
	FOREIGN KEY (ID_TIPO_EQUIPAMENTO)
	REFERENCES CG_TIPO_EQUIPAMENTO(ID_TIPO_EQUIPAMENTO)
GO

ALTER TABLE CG_EQUIPAMENTO
	ADD CONSTRAINT FK_CG_EQUIPAMENTO_2
	FOREIGN KEY (ID_FORNECEDOR)
	REFERENCES CG_FORNECEDOR(ID_FORNECEDOR)
GO