USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_ESTOQUE_CHIP]    Script Date: 13/11/2017 16:49:31 ******/
DROP VIEW [dbo].[VW_CG_ESTOQUE_CHIP]
GO

/****** Object:  View [dbo].[VW_CG_ESTOQUE_CHIP]    Script Date: 13/11/2017 16:49:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW [dbo].[VW_CG_ESTOQUE_CHIP]
AS
SELECT
    A.ID_CHIP, 
    B.SIMID, 
    B.ID_OPERADORA, 
    C.DESC_OPERADORA, 
    A.ESTOQUE, 
    A.TRANSITO, 
    B.CUSTO, 
    A.ID_LOCAL, 
    L.NOME, 
    L.SIGLA,
    A.DATAMOV, 
    B.ID_LOCAL_ESTOQUE,
    L.CODIGO,
    L.LOJA_FISICA,
    L.ID_AREA,
    A.TIPO_LOCAL
    
FROM
    dbo.CG_ESTOQUE_CHIP AS A 
	   INNER JOIN
		  dbo.CG_CHIP AS B 
			 ON A.ID_CHIP = B.ID_CHIP 
	   INNER JOIN
		  dbo.CG_OPERADORA AS C 
			 ON B.ID_OPERADORA = C.ID_OPERADORA
	   LEFT JOIN (
			 SELECT 'T' AS TIPO_LOCAL, ID_TRANSITO AS ID_LOJA, 
			 NOME_TRANSITO AS SIGLA, NOME_TRANSITO AS NOME, 
			 CONVERT(VARCHAR,ID_TRANSITO) AS CODIGO, 
			 CAST(0 AS BIT ) AS LOJA_FISICA,
			 SPACE(8) AS ID_AREA FROM CG_TRANSITO
			 UNION 
			 --SELECT 'L' AS TIPO_LOCAL, 0 AS ID_LOJA, 'NÃO ALOCADO' AS SIGLA, 'NÃO ALOCADO' AS NOME, SPACE(10) AS CODIGO
			 --UNION 
			 SELECT 'L' AS TIPO_LOCAL, ID_LOJA, SIGLA, NOME, 
			 CODIGO, LOJA_FISICA, ID_AREA FROM CG_LOJA ) AS L 
				ON L.ID_LOJA = A.ID_LOCAL AND L.TIPO_LOCAL = A.TIPO_LOCAL



GO


