
INSERT INTO CG_MODULO (ID_MODULO,DESC_MODULO,USER_INS,DATA_INS,USER_UPD,DATA_UPD)
VALUES  (57,'MOVIMENTO TRANSITO CHIP',1,GETDATE(),1,GETDATE()),
	   (58,'BAIXA TRANSITO CHIP',1,GETDATE(),1,GETDATE()),
	   (59,'MOVIMENTO TRANSITO EQUIPAMENTO',1,GETDATE(),1,GETDATE()),
	   (60,'BAIXA TRANSITO EQUIPAMENTO',1,GETDATE(),1,GETDATE())
GO

UPDATE CG_SEQUENCIAL SET KEYID=60 WHERE TABELA='CG_MODULO'
GO

SELECT * FROM CG_MODULO WHERE ID_MODULO BETWEEN 57 AND 60

