CREATE TABLE CG_TRANSITO
(
ID_TRANSITO INT NOT NULL,
NOME_TRANSITO VARCHAR(40) NOT NULL,
INATIVO BIT NOT NULL CONSTRAINT DF_CG_TRANSITO_INATIVO DEFAULT(0)
)
GO

ALTER TABLE CG_TRANSITO 
ADD CONSTRAINT PK_CG_TRANSITO PRIMARY KEY (ID_TRANSITO)
GO

INSERT INTO CG_MODULO (ID_MODULO, DESC_MODULO, USER_INS, DATA_INS, USER_UPD, DATA_UPD) 
VALUES (56, 'TRANSITO', 1, GETDATE(), 1, GETDATE()) 
GO

UPDATE CG_SEQUENCIAL
SET KEYID=56
WHERE TABELA = 'CG_MODULO'
GO
