USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_CHIP]    Script Date: 05/11/2017 16:15:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_CG_CHIP]
AS
SELECT CG_CHIP.ID_CHIP,
       CG_CHIP.SIMID,
       CG_CHIP.ID_OPERADORA,
       CG_OPERADORA.DESC_OPERADORA,
       CG_CHIP.ID_FORNECEDOR,
	  CG_CHIP.CUSTO,
       CG_FORNECEDOR.NOME,
       CG_FORNECEDOR.SIGLA,
       CG_FORNECEDOR.UTILIZA_NFTS,
	  CG_CHIP.ID_LOCAL_ESTOQUE,
	  CG_CHIP.TIPO_LOCAL
FROM 
	CG_CHIP (NOLOCK)
LEFT JOIN 
	CG_OPERADORA (NOLOCK)
		ON CG_CHIP.ID_OPERADORA = CG_OPERADORA.ID_OPERADORA
LEFT JOIN 
	CG_FORNECEDOR (NOLOCK)
		ON CG_CHIP.ID_FORNECEDOR = CG_FORNECEDOR.ID_FORNECEDOR


GO


