IF EXISTS( SELECT 1 FROM SYSOBJECTS WHERE TYPE='V' AND NAME = 'VW_CG_MOV_TRANSITO_CHIP')
BEGIN
    DROP VIEW VW_CG_MOV_TRANSITO_CHIP
END
GO

CREATE VIEW VW_CG_MOV_TRANSITO_CHIP
AS
select  M.ID_LANCTO, 
	   M.ID_TRANSITO, 
	   T.NOME_TRANSITO,
	   M.ID_ORIGEM, 
	   O.CODIGO AS CODIGO_ORIGEM,
	   O.NOME AS NOME_ORIGEM,
	   M.ID_CHIP, 
	   C.SIMID,
	   OP.DESC_OPERADORA,
	   M.QUANTIDADE, 
	   M.USER_INS, 
	   U.NOME AS NOME_USUARIO,
	   M.DATA_LANCTO, 
	   M.ID_DESTINO, 
	   L.CODIGO CODIGO_DESTINO,
	   L.NOME NOME_DESTINO,
	   M.DATA_MOV_DESTINO
from	   CG_MOV_TRANSITO_CHIP M
INNER JOIN 
	   CG_TRANSITO T ON T.ID_TRANSITO = M.ID_TRANSITO
INNER JOIN 
	   CG_CHIP C ON C.ID_CHIP = M.ID_CHIP
INNER JOIN 
	   CG_OPERADORA OP ON OP.ID_OPERADORA = C.ID_OPERADORA
INNER JOIN 
	   CG_USUARIO U ON U.ID_USUARIO = M.USER_INS
LEFT JOIN 
	   CG_LOJA L ON L.ID_LOJA = M.ID_DESTINO
LEFT JOIN 
	   CG_LOJA O ON O.ID_LOJA = M.ID_ORIGEM
GO

