IF EXISTS( SELECT 1 FROM SYSOBJECTS WHERE TYPE='V' AND NAME = 'VW_CG_MOV_TRANSITO_EQUIPAMENTO')
BEGIN
    DROP VIEW VW_CG_MOV_TRANSITO_EQUIPAMENTO
END
GO

CREATE VIEW VW_CG_MOV_TRANSITO_EQUIPAMENTO
AS
select  M.ID_LANCTO, 
	   M.ID_TRANSITO, 
	   T.NOME_TRANSITO,
	   M.ID_ORIGEM, 
	   O.CODIGO AS CODIGO_ORIGEM,
	   O.NOME AS NOME_ORIGEM,
	   M.ID_EQUIPAMENTO, 
	   E.SERIE,
	   E.DESC_EQUIPAMENTO,
	   E.MODELO,
	   M.QUANTIDADE, 
	   M.USER_INS, 
	   U.NOME AS NOME_USUARIO,
	   M.DATA_LANCTO, 
	   M.ID_DESTINO, 
	   L.CODIGO CODIGO_DESTINO,
	   L.NOME NOME_DESTINO,
	   M.DATA_MOV_DESTINO
from	   CG_MOV_TRANSITO_EQUIPAMENTO M
INNER JOIN 
	   CG_TRANSITO T ON T.ID_TRANSITO = M.ID_TRANSITO
INNER JOIN 
	   CG_EQUIPAMENTO E ON E.ID_EQUIPAMENTO = M.ID_EQUIPAMENTO
INNER JOIN 
	   CG_USUARIO U ON U.ID_USUARIO = M.USER_INS
LEFT JOIN 
	   CG_LOJA L ON L.ID_LOJA = M.ID_DESTINO
LEFT JOIN 
	   CG_LOJA O ON O.ID_LOJA = M.ID_ORIGEM
GO

