IF EXISTS( SELECT 1 FROM SYSOBJECTS WHERE TYPE='P' AND NAME = 'spLista_mov_transito_chip')
BEGIN
    DROP PROC spLista_mov_transito_chip
END
GO
CREATE PROCEDURE spLista_mov_transito_chip
(
    @ID_TRANSITO INT = NULL,
    @DATA1 DATETIME = NULL,
    @DATA2 DATETIME = NULL
)
as
SELECT  
    ID_TRANSITO 
    ,NOME_TRANSITO
    ,CODIGO_ORIGEM as CD_ORIGEM
    ,NOME_ORIGEM AS NM_ORIGEM
    ,SIMID 
    ,DESC_OPERADORA AS NM_OPERADORA
    ,QUANTIDADE AS QTD
    ,DATA_LANCTO AS DT_LANC
    ,ID_DESTINO 
    ,CODIGO_DESTINO AS CD_DEST
    ,NOME_DESTINO AS NM_DEST
    ,DATA_MOV_DESTINO AS DT_MOV_DEST
    ,ID_LANCTO 
    ,ID_ORIGEM
    ,ID_CHIP
    ,USER_INS
    ,NOME_USUARIO
FROM VW_CG_MOV_TRANSITO_CHIP 
WHERE 
    CONVERT(VARCHAR,DATA_LANCTO,112) BETWEEN CONVERT(VARCHAR,ISNULL(@DATA1,GETDATE()),112) AND CONVERT(VARCHAR,ISNULL(@DATA2,GETDATE()),112)
    AND ID_TRANSITO = ISNULL(@ID_TRANSITO, ID_TRANSITO)
ORDER BY NOME_TRANSITO ASC, DATA_LANCTO ASC
 