CREATE VIEW VW_CG_PEDIDOS_APROVACAO
AS
SELECT CG_CLIENTE.SIGLA, 
	   CG_PEDIDOVENDA_ITENS.ID_PEDIDO, 
       CG_EQUIPAMENTO.DESC_EQUIPAMENTO, 
       CG_EQUIPAMENTO.SERIE, 
       CG_PEDIDOVENDA_ITENS.QTDE, 
       CG_PEDIDOVENDA_ITENS.PRECO_VENDA, 
       CG_PEDIDOVENDA_ITENS.STATUS_ITEM, 
       CG_PEDIDOVENDA_ITENS.ID_EQUIPAMENTO, 
       CG_PEDIDOVENDA_ITENS.DATA_CADASTRO, 
       CG_PEDIDOVENDA_ITENS.DATA_BAIXA, 
       CG_PEDIDOVENDA_ITENS.ULTIMA_ALTERACAO, 
       CG_PEDIDOVENDA_ITENS.CANCEL, 
       CG_PEDIDOVENDA.ID_CLIENTE, 
       CG_CLIENTE.NOME, 
       CG_EQUIPAMENTO.ID_TIPO_EQUIPAMENTO, 
       CG_EQUIPAMENTO.MODELO, 
       CG_TIPO_EQUIPAMENTO.DESC_TIPO_EQUIPAMENTO 
FROM   CG_CLIENTE 
       INNER JOIN CG_PEDIDOVENDA 
               ON CG_CLIENTE.ID_CLIENTE = CG_PEDIDOVENDA.ID_CLIENTE 
       INNER JOIN CG_PEDIDOVENDA_ITENS 
               ON CG_PEDIDOVENDA.ID_PEDIDO = 
                  CG_PEDIDOVENDA_ITENS.ID_PEDIDO 
       INNER JOIN CG_EQUIPAMENTO 
               ON CG_PEDIDOVENDA_ITENS.ID_EQUIPAMENTO = 
                  CG_EQUIPAMENTO.ID_EQUIPAMENTO 
       INNER JOIN CG_TIPO_EQUIPAMENTO 
               ON CG_EQUIPAMENTO.ID_TIPO_EQUIPAMENTO = 
                  CG_TIPO_EQUIPAMENTO.ID_TIPO_EQUIPAMENTO 