select * from cg_loja where id_loja < 13

insert into CG_LOJA (ID_LOJA,SIGLA,NOME,ENDERECO,COMPLEMENTO,CEP,CIDADE,BAIRRO,UF,ID_TIPO_LOCAL, ID_RESPONSAVEL,USER_INS,DATA_INS,USER_UPD, DATA_UPD,CODIGO, TELEFONE, CELULAR, LOJA_FISICA, PARCERIA, ID_AREA, ID_TIPO_LOCAL_ESTOQUE, INATIVO, ULTIMA_ATUALIZACAO, INICIO_VIGENCIA, ID_EMPRESA)
SELECT 10 AS ID_LOJA,'ESTOQUE NO CLIENTE' SIGLA,'ESTOQUE NO CLIENTE' NOME,ENDERECO,COMPLEMENTO,CEP,CIDADE,BAIRRO,UF,ID_TIPO_LOCAL, ID_RESPONSAVEL,
USER_INS,GETDATE(),USER_UPD, GETDATE(),'0010', TELEFONE, CELULAR, LOJA_FISICA, PARCERIA, ID_AREA, 11 AS ID_TIPO_LOCAL_ESTOQUE, INATIVO, GETDATE(), GETDATE(), ID_EMPRESA
FROM CG_LOJA
WHERE ID_LOJA = 2

SELECT * FROM CG_TIPO_LOCAL_ESTOQUE
INSERT INTO CG_TIPO_LOCAL_ESTOQUE VALUES (11,'ESTOQUE NO CLIENTE')