alter table CG_ESTOQUE_EQUIPAMENTO
add PEDIDO_VENDA BIT NOT NULL CONSTRAINT DF_CG_ESTOQUE_EQUIPAMENTO_PEDIDO_VENDA DEFAULT(0)
GO

alter table CG_MOV_TRANSITO_EQUIPAMENTO
add PEDIDO_VENDA BIT NOT NULL CONSTRAINT DF_CG_MOV_TRANSITO_EQUIPAMENTO_PEDIDO_VENDA DEFAULT(0)
GO
