CREATE TABLE CG_ESTOQUE_CLIENTE (
ID_CLIENTE INT NOT NULL,
ID_EQUIPAMENTO INT NOT NULL,
ESTOQUE INT NOT NULL,
DATAMOV DATETIME NOT NULL,
TRANSITO BIT NOT NULL,
CONSTRAINT  PK_CG_ESTOQUE_CLIENTE PRIMARY KEY (ID_CLIENTE, ID_EQUIPAMENTO) 
)