USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_ESTOQUE_EQUIPAMENTO]    Script Date: 01/09/2019 09:48:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER VIEW [dbo].[VW_CG_ESTOQUE_EQUIPAMENTO]
AS
SELECT
    A.ID_EQUIPAMENTO, 
    B.SERIE, 
    B.MODELO, 
    B.DESC_EQUIPAMENTO, 
    A.ESTOQUE, 
    A.TRANSITO, 
    B.VALOR, 
    A.ID_LOCAL, 
    L.NOME, 
    L.SIGLA,
    A.DATAMOV, 
    B.ID_LOCAL_ESTOQUE,
    L.CODIGO,
    L.LOJA_FISICA,
    L.ID_AREA,
    A.TIPO_LOCAL,
	A.ID_EMPRESA,
	DBO.FX_LAST_ID_OS_ATIVA(A.ID_EQUIPAMENTO) AS ID_OS
FROM
    dbo.CG_ESTOQUE_EQUIPAMENTO AS A 
	   INNER JOIN
		  dbo.CG_EQUIPAMENTO AS B 
			 ON A.ID_EQUIPAMENTO = B.ID_EQUIPAMENTO
	   LEFT JOIN (
			 SELECT 'T' AS TIPO_LOCAL, ID_TRANSITO AS ID_LOJA, 
			 NOME_TRANSITO AS SIGLA, NOME_TRANSITO AS NOME, 
			 CONVERT(VARCHAR,ID_TRANSITO) AS CODIGO, 
			 CAST(0 AS BIT ) AS LOJA_FISICA,
			 SPACE(8) AS ID_AREA FROM CG_TRANSITO
			 UNION 
			 SELECT 'C' AS TIPO_LOCAL, ID_CLIENTE AS ID_LOJA, SIGLA, NOME, 
			 CONVERT(VARCHAR,ID_CLIENTE) AS CODIGO, CAST(0 AS BIT ) AS LOJA_FISICA, SPACE(8) AS ID_AREA FROM CG_CLIENTE
			 UNION
			 SELECT 'L' AS TIPO_LOCAL, ID_LOJA, SIGLA, NOME, 
			 CODIGO, LOJA_FISICA, ID_AREA FROM CG_LOJA ) AS L 
				ON L.ID_LOJA = A.ID_LOCAL AND L.TIPO_LOCAL = A.TIPO_LOCAL
             



--GO


GO


