
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER DBO.TGR_DEL_CG_PEDIDOVENDA_ITENS 
   ON  DBO.CG_PEDIDOVENDA_ITENS 
   FOR DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @TOT_QTDE_ENTREGAR INT, @TOT_QTDE_ORIGINAL INT
	SELECT @TOT_QTDE_ENTREGAR = A.TOT_QTDE_ENTREGAR, @TOT_QTDE_ORIGINAL = A.TOT_QTDE_ORIGINAL
	FROM CG_PEDIDOVENDA A
	INNER JOIN DELETED D ON D.ID_PEDIDO = A.ID_PEDIDO

	UPDATE A
	SET A.TOT_QTDE_ENTREGAR = @TOT_QTDE_ENTREGAR - 1, A.TOT_QTDE_ORIGINAL = @TOT_QTDE_ORIGINAL - 1  
	FROM CG_PEDIDOVENDA A
	INNER JOIN DELETED D ON D.ID_PEDIDO = A.ID_PEDIDO

END
GO
