
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER dbo.TGR_DEL_CG_ESTOQUE_CLIENTE 
   ON  dbo.CG_ESTOQUE_CLIENTE 
   FOR DELETE
AS 
BEGIN
	SET NOCOUNT ON;

	/*ACERTA O ESTOQUE - DEVOLVENDO O ITEM EXCLUIDO PARA O ESTOQUE DA MATRIZ*/
	UPDATE A
	SET A.ID_LOCAL=1, A.ID_EMPRESA=1, A.TIPO_LOCAL='L', A.PEDIDO_VENDA=0, A.DATAMOV = GETDATE()
	FROM CG_ESTOQUE_EQUIPAMENTO A 
	INNER JOIN DELETED B ON B.ID_EQUIPAMENTO = A.ID_EQUIPAMENTO

	/*ACERTA O PEDIDO - EXCLUINDO O ITEM PARA ACERTAR AS QUANTIDADES */
	DELETE A 
	FROM CG_PEDIDOVENDA_ITENS A
	INNER JOIN VW_CG_PEDIDOVENDA B ON B.ID_PEDIDO = A.ID_PEDIDO
	INNER JOIN DELETED D ON D.ID_EQUIPAMENTO = A.ID_EQUIPAMENTO AND D.ID_CLIENTE = B.ID_CLIENTE
	

END
GO


