SELECT * FROM CG_ESTOQUE_EQUIPAMENTO where DATAMOV >= '20190825'

SELECT * FROM CG_MOV_TRANSITO_EQUIPAMENTO A where A.DATA_LANCTO >= '20190825'

SELECT  
A.ID_EQUIPAMENTO,SERIE,DESC_EQUIPAMENTO,MODELO,1 AS QTD, VALOR , ID_LOCAL_ESTOQUE AS ID_TRANSITO, A.TIPO_LOCAL, A.ID_EMPRESA, 
 SPACE(10) as ID_DESTINO,  B.PEDIDO_VENDA 
FROM VW_CG_EQUIPAMENTO A
INNER JOIN CG_ESTOQUE_EQUIPAMENTO B ON B.ID_EQUIPAMENTO = A.ID_EQUIPAMENTO 
WHERE A.TIPO_LOCAL = 'T'


--select * from CG_EQUIPAMENTO where id_equipamento in (81,82)

select distinct tipo_local from CG_ESTOQUE_EQUIPAMENTO

select tipo_local, count(*) as qty from CG_EQUIPAMENTO group by tipo_local

EXEC spLista_mov_transito_chip  @ID_TRANSITO = NULL ,  @DATA1 = '20190825',  @DATA2 = '20190825',  @ID_EMPRESA = 1

EXEC spLista_mov_transito_equipamento @ID_TRANSITO = NULL , @DATA1 = '20190825', @DATA2 = '20190825', @ID_EMPRESA = 1


select * from cg_transito

select * from VW_CG_LOJA where id_loja = id_loja

SELECT * FROM CG_ESTOQUE_EQUIPAMENTO ORDER BY DATAMOV DESC

SELECT * FROM CG_EQUIPAMENTO WHERE ID_EQUIPAMENTO IN (205,206)


SELECT CG_PEDIDOVENDA.ID_CLIENTE FROM CG_PEDIDOVENDA_ITENS 
INNER JOIN CG_PEDIDOVENDA ON CG_PEDIDOVENDA.ID_PEDIDO = CG_PEDIDOVENDA_ITENS.ID_PEDIDO
INNER JOIN CG_CLIENTE ON CG_CLIENTE.ID_CLIENTE = CG_PEDIDOVENDA.ID_CLIENTE
WHERE ID_EQUIPAMENTO=115


SELECT * FROM CG_ESTOQUE_CLIENTE