CREATE TABLE CG_EQUIPAMENTO_VS_CHIP (
ID_EQUIPAMENTO INT NOT NULL,
ID_CHIP INT NOT NULL, 
USER_UPD INT NULL,
DATA_UPD DATETIME NULL
)
GO

ALTER TABLE CG_EQUIPAMENTO_VS_CHIP 
ADD PRIMARY KEY (ID_EQUIPAMENTO, ID_CHIP)
GO

ALTER TABLE CG_EQUIPAMENTO_VS_CHIP
ADD FOREIGN KEY (ID_EQUIPAMENTO)
REFERENCES CG_EQUIPAMENTO(ID_EQUIPAMENTO)
GO