alter table CG_LOJA
ADD CODIGO VARCHAR(10) NULL
GO

UPDATE CG_LOJA SET CODIGO = RIGHT('0000'+CONVERT(VARCHAR,ID_LOJA),4)
GO

ALTER TABLE CG_LOJA
ALTER COLUMN CODIGO VARCHAR(10) NOT NULL
GO

ALTER TABLE CG_LOJA
ADD UNIQUE (CODIGO)
GO
