UPDATE CG_CHIP SET ID_LOCAL_ESTOQUE = 0 WHERE ID_LOCAL_ESTOQUE IS NULL
GO

alter table CG_CHIP
ALTER COLUMN ID_LOCAL_ESTOQUE INT NOT NULL 
GO

ALTER TABLE CG_CHIP 
ADD CONSTRAINT DF_ID_LOCAL_ESTOQUE_1 DEFAULT (0) FOR ID_LOCAL_ESTOQUE 
GO