UPDATE CG_EQUIPAMENTO SET ID_LOCAL_ESTOQUE = 0 WHERE ID_LOCAL_ESTOQUE IS NULL
GO

alter table CG_EQUIPAMENTO
ALTER COLUMN ID_LOCAL_ESTOQUE INT NOT NULL 
GO

ALTER TABLE CG_EQUIPAMENTO 
ADD CONSTRAINT DF_ID_LOCAL_ESTOQUE_2 DEFAULT (0) FOR ID_LOCAL_ESTOQUE 
GO