ALTER TABLE [CG_LOJA_HISTORICO] NOCHECK CONSTRAINT ALL
GO

ALTER TABLE [CG_LOJA] NOCHECK CONSTRAINT ALL
GO

ALTER TABLE CG_AREA
ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_AREA_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

UPDATE CG_AREA SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_AREA
SET ID_EMPRESA = 4
where ID_AREA IN ('0004'
,'01'
,'02'
,'03'
,'04'
,'05'
,'06'
,'07'
,'08'
,'09'
,'10'
,'12'
,'13'
,'19') AND ID_EMPRESA = 1
GO

ALTER TABLE CG_LOJA_HISTORICO
ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_LOJA_HISTORICO_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

UPDATE CG_LOJA_HISTORICO SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_LOJA_HISTORICO
SET ID_EMPRESA = 4
WHERE ID_EMPRESA = 1
GO


UPDATE CG_LOJA SET ID_EMPRESA = 8
WHERE ID_EMPRESA = 4 AND ID_LOJA IN (871,1200)
GO

UPDATE B
SET ID_EMPRESA = 4
FROM cg_loja B
inner join CG_TIPO_LOCAL_ESTOQUE c on c.ID_TIPO_LOCAL_ESTOQUE = b.ID_TIPO_LOCAL_ESTOQUE
where B.id_empresa = 1 and b.ID_TIPO_LOCAL_ESTOQUE in (10) AND ID_LOJA > 12
GO

SELECT * FROM CG_LOJA WHERE ID_EMPRESA = 4
ALTER TABLE [CG_LOJA_HISTORICO] CHECK CONSTRAINT ALL
GO

ALTER TABLE [CG_LOJA] CHECK CONSTRAINT ALL
GO

--SELECT CODIGO,COUNT(*)
--FROM cg_loja B
--inner join CG_TIPO_LOCAL_ESTOQUE c on c.ID_TIPO_LOCAL_ESTOQUE = b.ID_TIPO_LOCAL_ESTOQUE
--where B.id_empresa = 1 and b.ID_TIPO_LOCAL_ESTOQUE in (10) AND ID_LOJA > 12
--GROUP BY CODIGO
