ALTER INDEX [UNQ_CG_EMPRESA_NOME] ON CG_EMPRESA DISABLE
GO
ALTER INDEX [UNQ_CG_EMPRESA_SIGLA] ON CG_EMPRESA DISABLE
GO

UPDATE CG_EMPRESA SET
NOME_EMPRESA = 'ORBIT SOLUTIONS', SIGLA_EMPRESA = 'ORBIT SOLUTIONS'
WHERE ID_EMPRESA = 1
GO

UPDATE CG_EMPRESA SET
NOME_EMPRESA = 'SR', SIGLA_EMPRESA = 'SR'
WHERE ID_EMPRESA = 4
GO

ALTER INDEX [UNQ_CG_EMPRESA_NOME] ON CG_EMPRESA REBUILD
GO
ALTER INDEX [UNQ_CG_EMPRESA_SIGLA] ON CG_EMPRESA REBUILD
GO

UPDATE CG_LOJA SET SIGLA = CASE WHEN ID_LOJA = 1 THEN 'MATRIZ ORBIT SOLUTIONS' WHEN ID_LOJA = 770 THEN 'MATRIZ SR' END,
NOME = CASE WHEN ID_LOJA = 1 THEN 'MATRIZ ORBIT SOLUTIONS' WHEN ID_LOJA = 770 THEN 'MATRIZ SR' END
WHERE ID_LOJA IN (1,770)
GO