CREATE TABLE CG_PECA (
    ID_PECA INT NOT NULL,
    NOME_PECA VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(250) NOT NULL,
    ID_MARCA INT NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    ID_FORNECEDOR INT NOT NULL,
    ID_FINALIDADE INT NOT NULL,
    ESTOQUE INT NULL,
    ESTOQUE_MIN INT NULL,
    ESTOQUE_MAX INT NULL,
    UNIDADE VARCHAR(10) NULL,
    DATA_AQUISICAO DATETIME NOT NULL,
    DIAS_GARANTIA INT NOT NULL,
    CUSTO NUMERIC (10,2) NULL,
    FOTO IMAGE NULL,
    REF_FORNEC VARCHAR(20) NULL,
    OBS TEXT NULL,
    USER_INS INT NULL,
    DATA_INS DATETIME NULL,
    USER_UPD INT NULL,
    DATA_UPD DATETIME)
GO

ALTER TABLE CG_PECA 
ADD CONSTRAINT PK_CG_PECA PRIMARY KEY (ID_PECA)
GO

ALTER TABLE CG_PECA 
ADD CONSTRAINT UNIQUE_CG_PECA_1 UNIQUE (NOME_PECA)
GO

ALTER TABLE CG_PECA
ADD CONSTRAINT FK_CG_PECA_MARCA
FOREIGN KEY (ID_MARCA) REFERENCES CG_MARCA(ID_MARCA)
GO

ALTER TABLE CG_PECA
ADD CONSTRAINT FK_CG_PECA_CATEGORIA
FOREIGN KEY (ID_CATEGORIA) REFERENCES CG_CATEGORIA(ID_CATEGORIA)
GO
 
ALTER TABLE CG_PECA
ADD CONSTRAINT FK_CG_PECA_FORNECEDOR
FOREIGN KEY (ID_FORNECEDOR) REFERENCES CG_FORNECEDOR(ID_FORNECEDOR)
GO

ALTER TABLE CG_PECA
ADD CONSTRAINT FK_CG_PECA_FINALIDADE
FOREIGN KEY (ID_FINALIDADE) REFERENCES CG_FINALIDADE(ID_FINALIDADE)
GO

ALTER TABLE CG_PECA
ADD CODIGO AS 'PC'+RIGHT('0000'+LTRIM(RTRIM(CONVERT(VARCHAR,ID_PECA))),4 ) 
GO

CREATE INDEX IX_CODIGO ON CG_PECA (CODIGO);
GO

ALTER TABLE CG_PECA
ADD FILETYPE VARCHAR(5) NULL
GO