
INSERT INTO CG_PARAMETRO_PESQUISA_DINAMICA
(TABELA, COLUNA, IDCOLUNA, ORDERCOL, CHAVE, TIPODADO, COLUNA_FILTRO, APELIDO_COLUNA, MOSTRA_COLUNA)
VALUES
('CG_MARCA', 'ID_MARCA', 1, 1, 0, 'Integer', 0, 'id_marca', 1),
('CG_MARCA', 'DESC_MARCA', 2, 2, 0, 'String', 1, 'desc_marca', 1)

