
INSERT INTO CG_PARAMETRO_PESQUISA_DINAMICA
(TABELA, COLUNA, IDCOLUNA, ORDERCOL, CHAVE, TIPODADO, COLUNA_FILTRO, APELIDO_COLUNA, MOSTRA_COLUNA)
VALUES
('CG_FINALIDADE', 'ID_FINALIDADE', 1, 1, 0, 'Integer', 0, 'id_FINALIDADE', 1),
('CG_FINALIDADE', 'DESC_FINALIDADE', 2, 2, 0, 'String', 1, 'desc_FINALIDADE', 1)

