CREATE TABLE CG_PEDIDO_COMPRA_PECA (
ID_PEDIDO INT NOT NULL,
TIPO_PEDIDO CHAR(2) NOT NULL,
STATUS_PEDIDO VARCHAR(10) NOT NULL,
ID_FORNECEDOR INT NOT NULL,
ID_COMPRADOR INT NOT NULL,
DATA_COMPRA DATETIME NOT NULL,
PREVISAO_ENTREGA DATETIME NOT NULL,
DATA_RECEBIMENTO DATETIME NULL,
OBS_PEDIDO TEXT NULL,
USER_INS INT NULL,
DATA_INS DATETIME NULL,
USER_UPD INT NULL,
DATA_UPD DATETIME NULL,
ROMANEIO_ESTOQUE INT NULL,
QTD_TOTAL INT NULL,
QTD_RECEBIDA INT NULL)
GO

ALTER TABLE CG_PEDIDO_COMPRA_PECA 
ADD CONSTRAINT PK_PEDIDO_COMPRA_PECA PRIMARY KEY (ID_PEDIDO)
GO

ALTER TABLE CG_PEDIDO_COMPRA_PECA 
ADD CONSTRAINT FK_PEDIDO_COMPRA_PECA_01
FOREIGN KEY (ID_FORNECEDOR) REFERENCES CG_FORNECEDOR (ID_FORNECEDOR)
GO

ALTER TABLE CG_PEDIDO_COMPRA_PECA 
ADD CONSTRAINT FK_PEDIDO_COMPRA_PECA_02
FOREIGN KEY (ID_COMPRADOR) REFERENCES CG_USUARIO (ID_USUARIO)
GO

CREATE TABLE CG_PEDIDO_COMPRA_PECA_ITEM (
ID_PEDIDO INT NOT NULL,
ID_PECA INT NOT NULL,
QTDE INT NOT NULL,
VALOR_UNIT NUMERIC(12,2) NOT NULL,
VALOR_TOTAL NUMERIC(12,2) NOT NULL,
RECEBIDO BIT NOT NULL DEFAULT(0),
DATA_RECEBIMENTO DATETIME NULL )
GO

ALTER TABLE CG_PEDIDO_COMPRA_PECA_ITEM
ADD CONSTRAINT PK_CG_PEDIDO_COMPRA_PECA_ITEM PRIMARY KEY (ID_PEDIDO, ID_PECA)
GO

ALTER TABLE CG_PEDIDO_COMPRA_PECA_ITEM
ADD CONSTRAINT FK_CG_PEDIDO_COMPRA_PECA_ITEM_1 
FOREIGN KEY (ID_PEDIDO) REFERENCES CG_PEDIDO_COMPRA_PECA (ID_PEDIDO)
GO

ALTER TABLE CG_PEDIDO_COMPRA_PECA_ITEM
ADD CONSTRAINT FK_CG_PEDIDO_COMPRA_PECA_ITEM_2
FOREIGN KEY (ID_PECA) REFERENCES CG_PECA (ID_PECA)
GO

