INSERT INTO CG_MODULO (ID_MODULO, DESC_MODULO, USER_INS, DATA_INS, USER_UPD, DATA_UPD)
VALUES (49, 'PEDIDO DE COMPRAS DE PEÇAS',1,GETDATE(),1,GETDATE() ), 
 (50, 'BAIXA DE PEDIDO DE COMPRAS DE PEÇAS', 1, GETDATE(), 1, GETDATE() )
 