UPDATE CG_SEQUENCIAL 
SET KEYID = 42 
WHERE TABELA = 'CG_MODULO'
GO

insert into CG_MODULO (ID_MODULO, DESC_MODULO, USER_INS, DATA_INS, USER_UPD, DATA_UPD)
VALUES (42, 'IMPORTAÇÃO CADASTRO DE LOJAS', 1, GETDATE(), 1, GETDATE())
GO



