CREATE TABLE CG_EQUIPAMENTO_HISTORICO_SERIE (
ID_EQUIPAMENTO INT NOT NULL,
DATA_ALTERACAO DATETIME NOT NULL DEFAULT (GETDATE()),
ID_OS INT NOT NULL,
ITEM_ID INT NOT NULL,
MOTIVO_ALTERACAO TEXT NOT NULL,
SERIE_ANTERIOR VARCHAR(30) NOT NULL,
SERIE_NOVA VARCHAR(30) NOT NULL)
GO

ALTER TABLE CG_EQUIPAMENTO_HISTORICO_SERIE
ADD PRIMARY KEY (ID_OS, ITEM_ID, ID_EQUIPAMENTO)
GO

ALTER TABLE CG_EQUIPAMENTO_HISTORICO_SERIE  
WITH CHECK ADD  CONSTRAINT [FK_CG_EQUIPAMENTO_HISTORICO_1] FOREIGN KEY(ID_OS, ITEM_ID, ID_EQUIPAMENTO)
REFERENCES [dbo].[CG_OS_ITEM] (ID_OS, ITEM_ID, ID_EQUIPAMENTO)
GO


