CREATE PROCEDURE spGravaCg_equipamento_historico_serie

    @ID_OS as int,
    @ITEM_ID as int,
    @ID_EQUIPAMENTO as int,
    @DATA_ALTERACAO as datetime,
    @MOTIVO_ALTERACAO as text,
    @SERIE_ANTERIOR as varchar(30),
    @SERIE_NOVA as varchar(30)

as
begin

    if exists(select 1 from CG_EQUIPAMENTO_HISTORICO_SERIE
			 where id_os = @ID_OS and item_id = @ITEM_ID and ID_EQUIPAMENTO = @ID_EQUIPAMENTO)
    begin

	   UPDATE 
		  CG_EQUIPAMENTO_HISTORICO_SERIE
	   SET 
		  DATA_ALTERACAO = @DATA_ALTERACAO, MOTIVO_ALTERACAO = @MOTIVO_ALTERACAO,
		  SERIE_ANTERIOR = @SERIE_ANTERIOR, SERIE_NOVA = @SERIE_NOVA
	   WHERE 
		  id_os = @ID_OS 
		  and item_id = @ITEM_ID 
		  and ID_EQUIPAMENTO = @ID_EQUIPAMENTO

    end
    ELSE
    begin
	   insert into 
		  CG_EQUIPAMENTO_HISTORICO_SERIE
			 (ID_EQUIPAMENTO, DATA_ALTERACAO, ID_OS, ITEM_ID, MOTIVO_ALTERACAO, SERIE_ANTERIOR, SERIE_NOVA)
		  values
			 (@ID_EQUIPAMENTO, @DATA_ALTERACAO, @ID_OS, @ITEM_ID, @MOTIVO_ALTERACAO, @SERIE_ANTERIOR, @SERIE_NOVA)
    end
end

UPDATE CG_EQUIPAMENTO SET SERIE = @SERIE_NOVA
WHERE ID_EQUIPAMENTO = @ID_EQUIPAMENTO

UPDATE CG_OS_ITEM
SET MUDOU_SERIE = 1
WHERE ID_OS = @ID_OS
	   AND ITEM_ID = @ITEM_ID
	   AND ID_EQUIPAMENTO = @ID_EQUIPAMENTO

go
