CREATE TABLE CG_EMPRESA_VS_USUARIOS (
ID_EMPRESA INT NOT NULL,
ID_USUARIO INT NOT NULL,
ID_PERFIL  INT NULL)
GO

ALTER TABLE CG_EMPRESA_VS_USUARIOS 
ADD CONSTRAINT PK_CG_EMPRESA_VS_USUARIOS PRIMARY KEY (ID_EMPRESA, ID_USUARIO)
GO

INSERT INTO CG_EMPRESA_VS_USUARIOS (ID_EMPRESA, ID_USUARIO)
SELECT 1, ID_USUARIO FROM CG_USUARIO 

INSERT INTO CG_EMPRESA_VS_USUARIOS (ID_EMPRESA, ID_USUARIO)
SELECT 2, ID_USUARIO FROM CG_USUARIO WHERE ID_USUARIO = 1



