CREATE TABLE CG_PERFIL (
ID_PERFIL INT NOT NULL,
DESC_PERFIL VARCHAR(50) NOT NULL)
GO

ALTER TABLE CG_PERFIL
ADD CONSTRAINT PK_CG_PERFIL PRIMARY KEY(ID_PERFIL)
GO

INSERT INTO CG_PERFIL VALUES (1, 'ADMINISTRADOR GERAL');

INSERT INTO CG_SEQUENCIAL VALUES ('CG_PERFIL',1,1,GETDATE(),1,GETDATE());

UPDATE CG_SEQUENCIAL SET KEYID = 67 WHERE TABELA = 'CG_TABELAS_PESQUISA_DINAMICA';

INSERT INTO CG_TABELAS_PESQUISA_DINAMICA VALUES (67,  'CG_PERFIL','T',0);

INSERT INTO [dbCG].[dbo].[CG_PARAMETRO_PESQUISA_DINAMICA] 
  (TABELA,COLUNA,IDCOLUNA,ORDERCOL,CHAVE,TIPODADO,COLUNA_FILTRO,APELIDO_COLUNA,MOSTRA_COLUNA,COLUNA_FILTRO_INICIAL)
  VALUES 
  ('CG_PERFIL','ID_PERFIL',1,1,1,'INT',1,'id_perfil',1,0),
  ('CG_PERFIL','DESC_PERFIL',2,2,0,'String',1,'desc_perfil',1,1)


INSERT INTO CG_MODULO VALUES (62,'PERFIL DE USUÁRIO',1,GETDATE(),1,GETDATE())

UPDATE CG_SEQUENCIAL SET KEYID = 62 WHERE TABELA = 'CG_MODULO';
