/*
EXEC spDuplicaUsuario
    @ID_USUARIO = 1,
    @NOME = 'NOME USUARIO NOVO',
    @APELIDO = 'APELIDO USUARIO NOVO',
    @LOGIN = 'DOMINIO\NOVOUSUARIO',
    @USER_INS = 1
*/
CREATE PROCEDURE spDuplicaUsuario
    @ID_USUARIO INT,
    @NOME VARCHAR(50),
    @APELIDO VARCHAR(50),
    @LOGIN VARCHAR(20),
    @USER_INS INT
AS
BEGIN

    DECLARE @NEW_USUARIO INT
    DECLARE @ID_STATUS INT
    DECLARE @DATA_INS DATETIME
    DECLARE @USER_UPD INT
    DECLARE @DATA_UPD DATETIME

    /*PEGA A NOVA CHAVE DO USUARIO*/
    DECLARE @TABLEID TABLE (NEWID INT) 
    INSERT INTO @TABLEID
    EXEC spNovaChave 'CG_USUARIO'

    SELECT @NEW_USUARIO = NEWID FROM @TABLEID

    SELECT 
	   @ID_STATUS = 1, 
	   @DATA_INS = GETDATE(), 
	   @USER_UPD = @USER_INS,  
	   @DATA_UPD = GETDATE()
    
    INSERT INTO CG_USUARIO
    (ID_USUARIO, APELIDO, NOME, LOGIN, ID_STATUS, USER_INS, DATA_INS, USER_UPD, DATA_UPD)
    VALUES 
    (@NEW_USUARIO, @APELIDO, @NOME, @LOGIN, @ID_STATUS, @USER_INS, @DATA_INS, @USER_UPD, @DATA_UPD)

    INSERT INTO CG_ACESSO 
    (ID_USUARIO, ID_MODULO, PERMISSAO, USER_INS, DATA_INS, USER_UPD, DATA_UPD)
    SELECT 
	   @NEW_USUARIO AS ID_USUARIO, 
	   ID_MODULO, 
	   PERMISSAO, 
	   @USER_INS AS USER_INS, 
	   GETDATE() AS DATA_INS, 
	   @USER_INS AS USER_UPD, 
	   GETDATE() AS DATA_UPD 
    FROM CG_ACESSO
    WHERE ID_USUARIO = @ID_USUARIO

END



