

CREATE TABLE CG_EMPRESA (
ID_EMPRESA INT NOT NULL CONSTRAINT PK_CG_EMPRESA PRIMARY KEY (ID_EMPRESA),
NOME_EMPRESA VARCHAR(60) NOT NULL CONSTRAINT UNQ_CG_EMPRESA_NOME UNIQUE (NOME_EMPRESA),
SIGLA_EMPRESA VARCHAR(20) NOT  NULL CONSTRAINT UNQ_CG_EMPRESA_SIGLA UNIQUE (SIGLA_EMPRESA),
ENDERECO_EMPRESA VARCHAR(80) NULL,
CEP_EMPRESA VARCHAR(10) NULL,
COMPLEMENTO_EMPRESA VARCHAR(40) NULL,
BAIRRO_EMPRESA VARCHAR(50) NULL,
CIDADE_EMPRESA VARCHAR(50) NULL,
UF_EMPRESA CHAR(2) NULL,
REFERENCIA_ENDERECO VARCHAR(150) NULL,
CONTATO_EMPRESA VARCHAR(50) NULL,
CELULAR_EMPRESA VARCHAR(20) NULL,
TELEFONE_EMPRESA VARCHAR(20) NULL,
OBSERVACAO TEXT NULL,
EMAIL VARCHAR(150) NULL )




