CREATE TABLE CG_PERFIL_MODULO (
ID_PERFIL INT NOT NULL,
ID_MODULO INT NOT NULL,
PESQUISAR BIT NOT NULL DEFAULT(0),
INCLUIR BIT NOT NULL DEFAULT(0),
ALTERAR BIT NOT NULL DEFAULT(0),
EXCLUIR BIT NOT NULL DEFAULT(0)
)
GO

ALTER TABLE CG_PERFIL_MODULO 
ADD CONSTRAINT PK_CG_PERFIL_MODULO PRIMARY KEY (ID_PERFIL, ID_MODULO)
GO

INSERT INTO CG_PERFIL_MODULO
SELECT 1, ID_MODULO, 1, 1, 1, 1
FROM CG_MODULO 
ORDER BY ID_MODULO
