ALTER TABLE CG_LOJA DROP CONSTRAINT FK_CG_LOJA_CG_AREA_01
GO

ALTER TABLE CG_AREA DROP CONSTRAINT PK_CG_AREA
GO

ALTER TABLE CG_AREA ADD CONSTRAINT PK_CG_AREA PRIMARY KEY (ID_AREA, ID_EMPRESA)
GO

ALTER TABLE CG_LOJA ADD CONSTRAINT FK_CG_LOJA_CG_AREA_01
FOREIGN KEY (ID_AREA, ID_EMPRESA) REFERENCES CG_AREA (ID_AREA, ID_EMPRESA);
GO