USE [dbCG]
GO

/****** Object:  Table [dbo].[CG_ENTRADA_ESTOQUE]    Script Date: 25/12/2017 17:19:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CG_ENTRADA_ESTOQUE](
	[ID_ROMANEIO] [int] NOT NULL,
	[DATA_MOVTO] [datetime] NOT NULL,
	[ID_LOJA] [int] NOT NULL,
	[USER_INS] [int] NULL,
	[DATA_INS] [datetime] NULL,
	[USER_UPD] [int] NULL,
	[DATA_UPD] [datetime] NULL,
	[ROMANEIO_ESTOQUE] [int] NULL,
	[ID_EMPRESA] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ROMANEIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CG_ENTRADA_ESTOQUE]  WITH CHECK ADD  CONSTRAINT [FK_CG_ENTRADA_ESTOQUE_1] FOREIGN KEY([ID_LOJA])
REFERENCES [dbo].[CG_LOJA] ([ID_LOJA])
GO

ALTER TABLE [dbo].[CG_ENTRADA_ESTOQUE] CHECK CONSTRAINT [FK_CG_ENTRADA_ESTOQUE_1]
GO


