

INSERT INTO CG_MODULO (ID_MODULO, DESC_MODULO, USER_INS, DATA_INS, USER_UPD, DATA_UPD)
VALUES (45, 'MARCAS',1,GETDATE(),1,GETDATE() ), 
 (46, 'CATEGORIAS', 1, GETDATE(), 1, GETDATE() ), 
 (47, 'FINALIDADES', 1, GETDATE(), 1, GETDATE()), 
 (48, 'PEÇAS', 1, GETDATE(), 1, GETDATE() )
