
INSERT INTO CG_SEQUENCIAL (TABELA, KEYID, USER_INS, DATA_INS, USER_UPD, DATA_UPD)
VALUES ('CG_MARCA',0,1,GETDATE(),1,GETDATE()),
('CG_CATEGORIA',0,1,GETDATE(),1,GETDATE()),
('CG_FINALIDADE',0,1,GETDATE(),1,GETDATE()),
('CG_PECA',0,1,GETDATE(),1,GETDATE())
