Public Class Cg_equipamento	Dim _id_equipamento As Integer	Dim _id_tipo_equipamento As Integer	Dim _desc_equipamento As String	Dim _serie As String	Dim _modelo As String	Dim _id_fornecedor As Integer	Dim _protocolo As String	Dim _valor As Decimal	Dim _obs As String	Dim _user_ins As Integer	Dim _data_ins As Date	Dim _user_upd As Integer    Dim _data_upd As Date    Dim _nf_entrada As String    Dim _data_nf As Date    Dim _prazo_garantia As Integer	Dim _id_empresa as Integer    Dim _preco_venda As Decimal?

    Property Id_empresa() As Integer		Get			Return _id_empresa		End Get		Set(ByVal value As Integer)			_id_empresa = value		End Set	End Property    Property NF_Entrada() As String        Get            Return _nf_entrada        End Get        Set(ByVal value As String)            _nf_entrada = value        End Set    End Property    Property Data_NF() As Date        Get            Return _data_nf        End Get        Set(ByVal value As Date)            _data_nf = value        End Set    End Property    Property Prazo_garantia() As Integer        Get            Return _prazo_garantia        End Get        Set(ByVal value As Integer)            _prazo_garantia = value        End Set    End Property	Property Id_equipamento() As Integer		Get			Return _id_equipamento		End Get		Set(ByVal value As Integer)			_id_equipamento = value		End Set	End Property	Property Id_tipo_equipamento() As Integer		Get			Return _id_tipo_equipamento		End Get		Set(ByVal value As Integer)			_id_tipo_equipamento = value		End Set	End Property	Property Desc_equipamento() As String		Get			Return _desc_equipamento		End Get		Set(ByVal value As String)			_desc_equipamento = value		End Set	End Property	Property Serie() As String		Get			Return _serie		End Get		Set(ByVal value As String)			_serie = value		End Set	End Property	Property Modelo() As String		Get			Return _modelo		End Get		Set(ByVal value As String)			_modelo = value		End Set	End Property	Property Id_fornecedor() As Integer		Get			Return _id_fornecedor		End Get		Set(ByVal value As Integer)			_id_fornecedor = value		End Set	End Property	Property Protocolo() As String		Get			Return _protocolo		End Get		Set(ByVal value As String)			_protocolo = value		End Set	End Property	Property Valor() As Decimal		Get			Return _valor		End Get		Set(ByVal value As Decimal)			_valor = value		End Set	End Property	Property Obs() As String		Get			Return _obs		End Get		Set(ByVal value As String)			_obs = value		End Set	End Property	Property User_ins() As Integer		Get			Return _user_ins		End Get		Set(ByVal value As Integer)			_user_ins = value		End Set	End Property	Property Data_ins() As Date		Get			Return _data_ins		End Get		Set(ByVal value As Date)			_data_ins = value		End Set	End Property	Property User_upd() As Integer		Get			Return _user_upd		End Get		Set(ByVal value As Integer)			_user_upd = value		End Set	End Property	Property Data_upd() As Date		Get			Return _data_upd		End Get		Set(ByVal value As Date)			_data_upd = value		End Set	End Property

    Property PrecoVenda() As Decimal?
        Get
            Return _preco_venda
        End Get
        Set(ByVal value As Decimal?)
            _preco_venda = value
        End Set
    End PropertyEnd Class