CREATE VIEW VW_CG_EQUIPAMENTO
AS
SELECT A.ID_EQUIPAMENTO,
       A.DESC_EQUIPAMENTO,
       A.SERIE,
       A.MODELO,
       A.ID_TIPO_EQUIPAMENTO,
       B.DESC_TIPO_EQUIPAMENTO,
       A.ID_FORNECEDOR,
       C.SIGLA,
       C.UTILIZA_NFTS,
       C.NOME,
       A.PROTOCOLO,
       A.VALOR,
       A.OBS
FROM 
	CG_EQUIPAMENTO AS A (NOLOCK)
LEFT JOIN 
	CG_TIPO_EQUIPAMENTO AS B (NOLOCK)
		ON A.ID_TIPO_EQUIPAMENTO = B.ID_TIPO_EQUIPAMENTO
LEFT JOIN 
	CG_FORNECEDOR AS C (NOLOCK)
		ON A.ID_FORNECEDOR = C.ID_FORNECEDOR