CREATE VIEW VW_CG_ACESSO
AS

	SELECT 
		A.ID_USUARIO, 
		B.APELIDO,
		B.NOME,
		A.ID_MODULO, 
		C.DESC_MODULO,
		A.PERMISSAO
	FROM 
		CG_ACESSO A (NOLOCK)
	LEFT JOIN 
		CG_USUARIO B (NOLOCK)
			ON B.ID_USUARIO = A.ID_USUARIO
	LEFT JOIN 
		CG_MODULO C (NOLOCK)
			ON C.ID_MODULO = A.ID_MODULO


		