USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_ESTOQUE_CHIP]    Script Date: 01/05/2017 18:56:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_CG_ESTOQUE_CHIP]
AS
SELECT
    A.ID_CHIP, 
    B.SIMID, 
    B.ID_OPERADORA, 
    C.DESC_OPERADORA, 
    A.ESTOQUE, 
    A.TRANSITO, 
    B.CUSTO, 
    A.ID_LOCAL, 
    L.NOME, 
    L.SIGLA,
    A.DATAMOV, 
    B.ID_LOCAL_ESTOQUE,
    L.CODIGO
    
FROM
    dbo.CG_ESTOQUE_CHIP AS A 
	   INNER JOIN
		  dbo.CG_CHIP AS B 
			 ON A.ID_CHIP = B.ID_CHIP 
	   INNER JOIN
		  dbo.CG_OPERADORA AS C 
			 ON B.ID_OPERADORA = C.ID_OPERADORA
	   LEFT JOIN (
			 SELECT 0 AS ID_LOJA, 'NÃO ALOCADO' AS SIGLA, 'NÃO ALOCADO' AS NOME, SPACE(10) AS CODIGO
			 UNION 
			 SELECT ID_LOJA, SIGLA, NOME, CODIGO FROM CG_LOJA ) AS L 
				ON L.ID_LOJA = A.ID_LOCAL

GO


