CREATE VIEW VW_CG_RESPONSAVEL
AS
SELECT A.ID_RESPONSAVEL,
       A.NOME,
       A.APELIDO,
       A.EMAIL,
       A.CELULAR,
       A.WHATSAPP,
       A.ID_CARGO,
       B.DESC_CARGO
FROM 
	CG_RESPONSAVEL AS A
LEFT JOIN 
	CG_CARGO AS B 
		ON A.ID_CARGO = B.ID_CARGO