CREATE VIEW VW_CG_DEVOLUCAO_CHIP_ITEM
AS
SELECT A.ID_ROMANEIO,
       A.UNIQUE_KEYID,
       A.ID_CHIP,
       A.SIMID,
       B.ID_OPERADORA,
       D.DESC_OPERADORA,
       B.ID_FORNECEDOR,
       E.SIGLA,
       E.UTILIZA_NFTS,
       E.NOME,
       A.QTD,
       A.VALOR,
       A.ID_MOTIVO,
       C.DESC_MOTIVO
FROM 
	CG_DEVOLUCAO_CHIP_ITEM AS A (NOLOCK)
LEFT JOIN 
	CG_CHIP AS B (NOLOCK)
		ON A.ID_CHIP = B.ID_CHIP
LEFT JOIN 
	CG_MOTIVO AS C (NOLOCK)
		ON A.ID_MOTIVO = C.ID_MOTIVO
LEFT JOIN 
	CG_OPERADORA AS D (NOLOCK)
		ON B.ID_OPERADORA = D.ID_OPERADORA
LEFT JOIN 
	CG_FORNECEDOR AS E (NOLOCK)
		ON B.ID_FORNECEDOR = E.ID_FORNECEDOR
GO
