CREATE VIEW VW_CG_EQUIPAMENTO_VS_CHIP
AS
SELECT A.ID_EQUIPAMENTO,
       B.DESC_EQUIPAMENTO,
       B.SERIE,
       B.MODELO,
       A.ID_CHIP,
       C.SIMID,
       C.ID_OPERADORA,
       D.DESC_OPERADORA,
       E.APELIDO,
       E.NOME
FROM dbo.CG_EQUIPAMENTO_VS_CHIP (NOLOCK) AS A
LEFT JOIN dbo.CG_EQUIPAMENTO (NOLOCK)  AS B ON B.ID_EQUIPAMENTO = A.ID_EQUIPAMENTO
LEFT JOIN dbo.CG_CHIP (NOLOCK)  AS C ON C.ID_CHIP = A.ID_CHIP
LEFT JOIN dbo.CG_OPERADORA (NOLOCK)  AS D ON D.ID_OPERADORA = C.ID_OPERADORA
LEFT JOIN dbo.CG_USUARIO (NOLOCK)  AS E ON E.ID_USUARIO = A.USER_UPD
GO


