CREATE VIEW VW_CG_FORNECEDOR
AS
SELECT A.ID_FORNECEDOR,
       A.SIGLA,
       A.UTILIZA_NFTS,
       A.NOME,
       A.CEP,
       A.ENDERECO,
       A.COMPLEMENTO,
       A.CIDADE,
       A.BAIRRO,
       A.UF,
       A.EMAIL,
       A.TELEFONE,
       A.CONTATO,
       A.WHATSAPP,
       A.ID_TIPO_SERVICO,
       A.OBS,
       B.DESC_TIPO_SERVICO
FROM 
	CG_FORNECEDOR AS A (NOLOCK)
LEFT JOIN 
	CG_TIPO_SERVICO AS B (NOLOCK)
		ON A.ID_TIPO_SERVICO = B.ID_TIPO_SERVICO