CREATE VIEW VW_CG_CHIP
AS
SELECT CG_CHIP.ID_CHIP,
       CG_CHIP.SIMID,
       CG_CHIP.ID_OPERADORA,
       CG_OPERADORA.DESC_OPERADORA,
       CG_CHIP.ID_FORNECEDOR,
	  CG_CHIP.CUSTO,
       CG_FORNECEDOR.NOME,
       CG_FORNECEDOR.SIGLA,
       CG_FORNECEDOR.UTILIZA_NFTS
FROM 
	CG_CHIP (NOLOCK)
LEFT JOIN 
	CG_OPERADORA (NOLOCK)
		ON CG_CHIP.ID_OPERADORA = CG_OPERADORA.ID_OPERADORA
LEFT JOIN 
	CG_FORNECEDOR (NOLOCK)
		ON CG_CHIP.ID_FORNECEDOR = CG_FORNECEDOR.ID_FORNECEDOR
GO