CREATE VIEW VW_CG_DEVOLUCAO_EQUIPAMENTO_ITEM
AS
SELECT A.ID_ROMANEIO,
       A.UNIQUE_KEYID,
       A.ID_EQUIPAMENTO,
       B.DESC_EQUIPAMENTO,
       B.SERIE,
       B.MODELO,
       B.ID_FORNECEDOR,
       D.DESC_TIPO_EQUIPAMENTO,
       A.QTD,
       A.VALOR,
       A.ID_MOTIVO,
       C.DESC_MOTIVO,
       E.SIGLA,
       E.UTILIZA_NFTS,
       E.NOME
FROM CG_DEVOLUCAO_EQUIPAMENTO_ITEM AS A (NOLOCK)
LEFT JOIN 
	CG_EQUIPAMENTO AS B (NOLOCK)
		ON A.ID_EQUIPAMENTO = B.ID_EQUIPAMENTO
LEFT JOIN 
	CG_MOTIVO AS C (NOLOCK)
		ON A.ID_MOTIVO = C.ID_MOTIVO
LEFT JOIN 
	CG_TIPO_EQUIPAMENTO AS D (NOLOCK)
		ON B.ID_TIPO_EQUIPAMENTO = D.ID_TIPO_EQUIPAMENTO
LEFT JOIN 
	CG_FORNECEDOR AS E (NOLOCK)
		ON B.ID_FORNECEDOR = E.ID_FORNECEDOR