USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_ENTRADA_CHIP]    Script Date: 07/08/2016 07:48:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_CG_ENTRADA_EQUIPAMENTO]
AS
SELECT A.ID_ROMANEIO,
       A.DATA_MOVTO,
       A.ID_LOJA,
       B.SIGLA,
       B.NOME,
       B.ID_TIPO_LOCAL,
       C.DESC_ALOCACAO,
       B.ID_RESPONSAVEL,
       D.NOME AS RESPONSAVEL,
       D.APELIDO
FROM 
	CG_ENTRADA_EQUIPAMENTO AS A (NOLOCK)
LEFT JOIN 
	CG_LOJA AS B (NOLOCK)
		ON A.ID_LOJA = B.ID_LOJA
LEFT JOIN 
	CG_ALOCACAO AS C (NOLOCK)
		ON B.ID_TIPO_LOCAL = C.ID_ALOCACAO
LEFT JOIN 
	CG_RESPONSAVEL AS D (NOLOCK)
		ON B.ID_RESPONSAVEL = D.ID_RESPONSAVEL
GO

