USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_ESTOQUE_EQUIPAMENTO]    Script Date: 01/05/2017 19:56:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_CG_ESTOQUE_EQUIPAMENTO]
AS
SELECT
    A.ID_EQUIPAMENTO, 
    B.SERIE, 
    B.MODELO, 
    B.DESC_EQUIPAMENTO, 
    A.ESTOQUE, 
    A.TRANSITO, 
    B.VALOR, 
    A.ID_LOCAL, 
    L.NOME, 
    L.SIGLA,
    A.DATAMOV, 
    B.ID_LOCAL_ESTOQUE,
    L.CODIGO

FROM
    dbo.CG_ESTOQUE_EQUIPAMENTO AS A 
	   INNER JOIN
		  dbo.CG_EQUIPAMENTO AS B 
			 ON A.ID_EQUIPAMENTO = B.ID_EQUIPAMENTO 
	   LEFT JOIN (
			 SELECT 0 AS ID_LOJA, 'NÃO ALOCADO' AS SIGLA, 'NÃO ALOCADO' AS NOME, SPACE(10) AS CODIGO
			 UNION 
			 SELECT ID_LOJA, SIGLA, NOME, CODIGO FROM CG_LOJA ) AS L 
				ON L.ID_LOJA = A.ID_LOCAL

GO


