USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_LOJA]    Script Date: 29/04/2017 13:49:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_CG_LOJA]
AS
SELECT A.ID_LOJA,
       A.SIGLA,
       A.NOME,
       A.ENDERECO,
       A.COMPLEMENTO,
       A.CEP,
       A.CIDADE,
       A.BAIRRO,
       A.UF,
       A.ID_TIPO_LOCAL,
       B.DESC_ALOCACAO,
       A.ID_RESPONSAVEL,
       C.NOME AS RESPONSAVEL,
       C.APELIDO,
	  A.CODIGO
FROM 
	CG_LOJA AS A (NOLOCK)
LEFT JOIN 
	dbo.CG_ALOCACAO AS B (NOLOCK)
		ON A.ID_TIPO_LOCAL = B.ID_ALOCACAO
LEFT JOIN 
	dbo.CG_RESPONSAVEL AS C (NOLOCK)
		ON A.ID_RESPONSAVEL = C.ID_RESPONSAVEL
GO


