USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_EQUIPAMENTO_VS_CHIP]    Script Date: 25/01/2017 19:08:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_CG_EQUIPAMENTO_VS_CHIP_AGRUPADO]
AS
SELECT A.ID_EQUIPAMENTO,
       B.DESC_EQUIPAMENTO,
       B.SERIE,
       B.MODELO,
 	  COUNT(*) AS QTD_CHIP
FROM dbo.CG_EQUIPAMENTO_VS_CHIP (NOLOCK) AS A
LEFT JOIN dbo.CG_EQUIPAMENTO (NOLOCK)  AS B ON B.ID_EQUIPAMENTO = A.ID_EQUIPAMENTO

GROUP BY 
    A.ID_EQUIPAMENTO,
    B.DESC_EQUIPAMENTO,
    B.SERIE,
    B.MODELO

GO


