USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_EQUIPAMENTOS_DISPONIVEIS_DEVOLUCAO_MATRIZ]    Script Date: 02/04/2017 22:10:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[VW_CG_EQUIPAMENTOS_DISPONIVEIS_DEVOLUCAO_MATRIZ]
AS
SELECT CG_EQUIPAMENTO.ID_EQUIPAMENTO,
       CG_EQUIPAMENTO.SERIE,
       CG_EQUIPAMENTO.MODELO,
       CG_EQUIPAMENTO.DESC_EQUIPAMENTO,
       CG_EQUIPAMENTO.ID_FORNECEDOR,
       CG_FORNECEDOR.NOME,
       CG_FORNECEDOR.SIGLA,
       CG_FORNECEDOR.UTILIZA_NFTS,
	  CG_EQUIPAMENTO.ID_LOCAL_ESTOQUE,
	  CG_EQUIPAMENTO.VALOR
	  
FROM 
	CG_EQUIPAMENTO (NOLOCK)
LEFT JOIN 
	CG_FORNECEDOR (NOLOCK)
		ON CG_EQUIPAMENTO.ID_FORNECEDOR = CG_FORNECEDOR.ID_FORNECEDOR
WHERE 
    CG_EQUIPAMENTO.ID_LOCAL_ESTOQUE = 1 AND 
	(CG_EQUIPAMENTO.ID_EQUIPAMENTO NOT IN (SELECT A.ID_EQUIPAMENTO FROM CG_DEVOLUCAO_EQUIPAMENTO_ITEM A (NOLOCK)))


GO


