CREATE VIEW VW_ROMANEIO_ESTOQUE_ITEM_CHIP
AS
SELECT 

A.ROMANEIO, A.UNIQUE_KEY, A.ID_PRODUTO, B.SIMID, B.ID_OPERADORA, B.DESC_OPERADORA,
A.ENTRADA_SAIDA, A.QUANTIDADE, A.TRANSITO, 
A.ID_TRANSACAO, C.DESC_TRANSACAO,  A.ID_LOCAL_DE, L1.NOME NOME_ORIGEM, L1.SIGLA SIGLA_ORIGEM, 
A.ID_LOCAL_PARA, L2.NOME NOME_DESTINO, L2.SIGLA SIGLA_DESTINO, A.DATAMOV,  A.OBSERVACAO

FROM [dbo].[ROMANEIO_ESTOQUE_ITEM] A

LEFT JOIN [dbo].[CG_TRANSACOES_ESTOQUE] C 
    ON C.ID_TRANSACAO = A.ID_TRANSACAO

LEFT JOIN [dbo].[VW_CG_CHIP] B 
    ON B.ID_CHIP = A.ID_PRODUTO

LEFT JOIN (
    SELECT 0 AS ID_LOJA, 'NÃO ALOCADO' AS SIGLA, 'NÃO ALOCADO' AS NOME
    UNION 
    SELECT ID_LOJA, SIGLA, NOME FROM CG_LOJA ) AS L1 
	   ON L1.ID_LOJA = A.ID_LOCAL_DE

LEFT JOIN (
    SELECT 0 AS ID_LOJA, 'NÃO ALOCADO' AS SIGLA, 'NÃO ALOCADO' AS NOME
    UNION 
    SELECT ID_LOJA, SIGLA, NOME FROM CG_LOJA ) AS L2 
	   ON L2.ID_LOJA = A.ID_LOCAL_PARA

WHERE A.ID_TRANSACAO IN ('DEC','DIC','EEC','EIC','MEC','MIC','REC','RIC') /*FILTRA SOMENTE OPERAÇÃO DE CHIP*/