CREATE VIEW VW_ROMANEIO_ESTOQUE
AS

select 
ROMANEIO, MODULO, TIPO_PRODUTO, TIPO_OP, DATAMOV, A.ID_USUARIO, B.NOME
from [dbo].[ROMANEIO_ESTOQUE] A
LEFT JOIN 
    CG_USUARIO B
	   ON B.ID_USUARIO = A.ID_USUARIO