ALTER TABLE CG_CHIP ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_CHIP_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

ALTER TABLE CG_ENTRADA_CHIP ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_ENTRADA_CHIP_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

ALTER TABLE CG_ENTRADA_CHIP_ITEM ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_ENTRADA_CHIP_ITEM_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

ALTER TABLE CG_ENTRADA_EQUIPAMENTO ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_ENTRADA_EQUIPAMENTO_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

ALTER TABLE CG_ENTRADA_EQUIPAMENTO_ITEM ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_ENTRADA_EQUIPAMENTO_ITEM_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

ALTER TABLE CG_EQUIPAMENTO ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_EQUIPAMENTO_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

ALTER TABLE CG_FORNECEDOR ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_FORNECEDOR_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

ALTER TABLE CG_LOJA ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_LOJA_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

ALTER TABLE CG_OS ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_OS_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

ALTER TABLE CG_OS_ITEM ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_OS_ITEM_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO
