--select 'UPDATE '+ tabela + ' SET ID_EMPRESA  = 4 WHERE  id_empresa_old = @id_empresa ' from CG_TABELAS_PESQUISA_DINAMICA SET ID_EMPRESA  = 4 WHERE  FILTRA_POR_EMPRESA=1  AND TIPO_TABELA='T'

UPDATE CG_TABELAS_PESQUISA_DINAMICA SET ID_EMPRESA  = 4 WHERE  FILTRA_POR_EMPRESA=1 AND TIPO_TABELA='T'


select 'ALTER TABLE '+ TABELA + ' ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_'+RTRIM(TABELA)+'_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;' 
from CG_TABELAS_PESQUISA_DINAMICA SET ID_EMPRESA  = 4 WHERE  FILTRA_POR_EMPRESA=1 AND TIPO_TABELA='T'

select 'UPDATE '+TABELA+' SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR,GETDATE(),112);'
from CG_TABELAS_PESQUISA_DINAMICA WHERE  FILTRA_POR_EMPRESA=1 AND TIPO_TABELA='T'

update CG_TABELAS_PESQUISA_DINAMICA set FILTRA_POR_EMPRESA = 0 WHERE  tabela in (
'CG_CATEGORIA','CG_FINALIDADE','CG_FOLLOW_UP','CG_MARCA', 'CG_RESPONSAVEL'
)
GO
disable TRIGGER ALL ON DATABASE
GO

/*
declare @id_empresa int = 4
UPDATE CG_CHIP SET ID_EMPRESA  = 4 WHERE  id_empresa_old = @id_empresa 
UPDATE CG_ENTRADA_CHIP SET ID_EMPRESA  = 4 WHERE  id_empresa_old = @id_empresa 
UPDATE CG_ENTRADA_CHIP_ITEM SET ID_EMPRESA  = 4 WHERE  id_empresa_old = @id_empresa 
UPDATE CG_ENTRADA_EQUIPAMENTO SET ID_EMPRESA  = 4 WHERE  id_empresa_old = @id_empresa 
UPDATE CG_ENTRADA_EQUIPAMENTO_ITEM SET ID_EMPRESA  = 4 WHERE  id_empresa_old = @id_empresa 
UPDATE CG_EQUIPAMENTO SET ID_EMPRESA  = 4 WHERE  id_empresa_old = @id_empresa 
UPDATE CG_FORNECEDOR SET ID_EMPRESA  = 4 WHERE  id_empresa_old = @id_empresa 
UPDATE CG_LOJA SET ID_EMPRESA  = 4 WHERE  id_empresa_old = @id_empresa 
UPDATE CG_OS SET ID_EMPRESA  = 4 WHERE  id_empresa_old = @id_empresa 
UPDATE CG_OS_ITEM SET ID_EMPRESA  = 4 WHERE  id_empresa_old = @id_empresa 
*/
declare @id_empresa int = 1
UPDATE CG_CHIP SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR,GETDATE(),112) WHERE  id_empresa_old = @id_empresa  ;
UPDATE CG_ENTRADA_CHIP SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR,GETDATE(),112) WHERE  id_empresa_old = @id_empresa  ;
UPDATE CG_ENTRADA_CHIP_ITEM SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR,GETDATE(),112) WHERE  id_empresa_old = @id_empresa  ;
UPDATE CG_ENTRADA_EQUIPAMENTO SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR,GETDATE(),112) WHERE  id_empresa_old = @id_empresa  ;
UPDATE CG_ENTRADA_EQUIPAMENTO_ITEM SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR,GETDATE(),112) WHERE  id_empresa_old = @id_empresa  ;
UPDATE CG_EQUIPAMENTO SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR,GETDATE(),112) WHERE  id_empresa_old = @id_empresa  ;
UPDATE CG_FORNECEDOR SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR,GETDATE(),112) WHERE  id_empresa_old = @id_empresa  ;
UPDATE CG_LOJA SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR,GETDATE(),112) WHERE  id_empresa_old = @id_empresa  ;
UPDATE CG_OS SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR,GETDATE(),112) WHERE  id_empresa_old = @id_empresa  ;
UPDATE CG_OS_ITEM SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR,GETDATE(),112) WHERE  id_empresa_old = @id_empresa  ;


 Select (Select name from sysobjects x SET ID_EMPRESA  = 4 WHERE  x.id=tr.parent_obj) Tabela, Name as NomeTrigger, 
      ObjectProperty(Object_id(Name),'ExecIsTriggerdisabled') Habilitado 
From sysobjects tr
SET ID_EMPRESA  = 4 WHERE  xtype = 'tr' and name not like 'log%' 
-- Na linha acima, na parte do NAME NOT LIKE, eliminamos as triggers que são do log de auditoria. 
-- Se quiser visualizar estes também, deixe no SET ID_EMPRESA  = 4 WHERE  apenas a parte XTYPE = 'TR'
Order by Tabela, Name

SELECT
'ALTER TABLE' + ' ' + OBJECT_NAME(PARENT_OBJ) + ' disable TRIGGER ' + NAME +';'
FROM
SYSOBJECTS
SET ID_EMPRESA  = 4 WHERE 
(XTYPE = 'TR')
AND NAME NOT LIKE 'LOG%' AND
OBJECTPROPERTY(OBJECT_ID(NAME),'EXECISTRIGGERdisableD') = 0
ORDER BY
OBJECT_NAME(PARENT_OBJ),
NAME