ALTER TABLE [CG_LOJA_HISTORICO] NOCHECK CONSTRAINT ALL
GO

ALTER TABLE [CG_LOJA] NOCHECK CONSTRAINT ALL
GO

ALTER TABLE CG_AREA
ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_AREA_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

UPDATE CG_AREA SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_AREA
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO

ALTER TABLE CG_LOJA_HISTORICO
ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_LOJA_HISTORICO_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

UPDATE CG_LOJA_HISTORICO SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_LOJA_HISTORICO
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO

UPDATE CG_LOJA
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO

ALTER TABLE [CG_LOJA_HISTORICO] CHECK CONSTRAINT ALL
GO

ALTER TABLE [CG_LOJA] CHECK CONSTRAINT ALL
GO

ALTER TABLE CG_ESTOQUE_CHIP
ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_ESTOQUE_CHIP_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

UPDATE CG_ESTOQUE_CHIP SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_ESTOQUE_CHIP
SET ID_EMPRESA = CASE
			WHEN ID_EMPRESA_OLD = 1 THEN 4
			WHEN ID_EMPRESA_OLD = 4 THEN 1
			ELSE ID_EMPRESA
		END
GO

UPDATE CG_CHIP SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
WHERE ID_EMPRESA IN (1,4)
GO

UPDATE CG_CHIP
SET ID_EMPRESA = CASE
			WHEN ID_EMPRESA_OLD = 1 THEN 4
			WHEN ID_EMPRESA_OLD = 4 THEN 1
			ELSE ID_EMPRESA
		END
GO

ALTER TABLE CG_ESTOQUE_EQUIPAMENTO
ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_ESTOQUE_EQUIPTO_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

UPDATE CG_ESTOQUE_EQUIPAMENTO SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_ESTOQUE_EQUIPAMENTO
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO

UPDATE CG_EQUIPAMENTO SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
WHERE ID_EMPRESA IN (1,4)
GO

--SELECT * FROM CG_CHIP
--WHERE ID_EMPRESA IN (1,4)

UPDATE CG_EQUIPAMENTO
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO

ALTER TABLE CG_MOV_TRANSITO_CHIP
ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_MOV_TRANSITO_CHIP_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

UPDATE CG_MOV_TRANSITO_CHIP SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_MOV_TRANSITO_CHIP
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO

ALTER TABLE CG_MOV_TRANSITO_EQUIPAMENTO
ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_MOV_TRANSITO_EQUIPAMENTO_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

UPDATE CG_MOV_TRANSITO_EQUIPAMENTO SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_MOV_TRANSITO_EQUIPAMENTO
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO

UPDATE CG_ENTRADA_CHIP_ITEM SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_ENTRADA_CHIP_ITEM
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO

UPDATE CG_ENTRADA_EQUIPAMENTO_ITEM SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_ENTRADA_EQUIPAMENTO_ITEM
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO

ALTER TABLE CG_ENTRADA_ESTOQUE
ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_ENTRADA_ESTOQUE_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

UPDATE CG_ENTRADA_ESTOQUE SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_ENTRADA_ESTOQUE
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO

UPDATE CG_FORNECEDOR SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_FORNECEDOR
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO

------------------OS
ALTER TABLE [CG_OS] NOCHECK CONSTRAINT ALL
GO
UPDATE CG_OS SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_OS
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO
ALTER TABLE [CG_OS] CHECK CONSTRAINT ALL
GO

----------------OS ITEM
ALTER TABLE [CG_OS_ITEM] NOCHECK CONSTRAINT ALL
GO
UPDATE CG_OS_ITEM SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_OS_ITEM
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO
ALTER TABLE [CG_OS_ITEM] CHECK CONSTRAINT ALL
GO

ALTER TABLE CG_RESPONSAVEL
ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_CG_RESPONSAVEL_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

UPDATE CG_RESPONSAVEL SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE CG_RESPONSAVEL
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO

ALTER TABLE ROMANEIO_ESTOQUE
ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_ROMANEIO_ESTOQUE_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

UPDATE ROMANEIO_ESTOQUE SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE ROMANEIO_ESTOQUE
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO

ALTER TABLE ROMANEIO_ESTOQUE_ITEM
ADD ID_EMPRESA_OLD INT NULL, DT_ALT_EMPRESA_OLD DATETIME NULL CONSTRAINT DF_ROMANEIO_ESTOQUE_ITEM_DT_ALT_EMPRESA_OLD DEFAULT (GETDATE()) ;
GO

UPDATE ROMANEIO_ESTOQUE_ITEM SET ID_EMPRESA_OLD = ID_EMPRESA, DT_ALT_EMPRESA_OLD = CONVERT(VARCHAR, GETDATE(),112)
GO

UPDATE ROMANEIO_ESTOQUE_ITEM
SET ID_EMPRESA = CASE
					WHEN ID_EMPRESA_OLD = 1 THEN 4
					WHEN ID_EMPRESA_OLD = 4 THEN 1
					ELSE ID_EMPRESA
				END
GO


ALTER INDEX [UNQ_CG_EMPRESA_NOME] ON CG_EMPRESA DISABLE
GO
ALTER INDEX [UNQ_CG_EMPRESA_SIGLA] ON CG_EMPRESA DISABLE
GO

UPDATE CG_EMPRESA SET
NOME_EMPRESA = 'ORBIT SOLUTIONS', SIGLA_EMPRESA = 'ORBIT SOLUTIONS'
WHERE ID_EMPRESA = 1
GO

UPDATE CG_EMPRESA SET
NOME_EMPRESA = 'SR', SIGLA_EMPRESA = 'SR'
WHERE ID_EMPRESA = 4
GO



ALTER INDEX [UNQ_CG_EMPRESA_NOME] ON CG_EMPRESA REBUILD
GO
ALTER INDEX [UNQ_CG_EMPRESA_SIGLA] ON CG_EMPRESA REBUILD
GO

UPDATE CG_LOJA SET SIGLA = CASE WHEN ID_LOJA = 1 THEN 'MATRIZ ORBIT SOLUTIONS' WHEN ID_LOJA = 770 THEN 'MATRIZ SR' END,
NOME = CASE WHEN ID_LOJA = 1 THEN 'MATRIZ ORBIT SOLUTIONS' WHEN ID_LOJA = 770 THEN 'MATRIZ SR' END
WHERE ID_LOJA IN (1,770)
GO

 UPDATE CG_ESTOQUE_EQUIPAMENTO SET ID_EMPRESA = 4 WHERE ID_EMPRESA = 1 AND ID_LOCAL = 770
 GO
