ALTER TABLE CG_ACESSO DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_ALOCACAO DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_AREA DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_CARGO DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_CATEGORIA DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_CHIP DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_ENTRADA_CHIP DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_ENTRADA_CHIP_ITEM DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_ENTRADA_EQUIPAMENTO DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_ENTRADA_EQUIPAMENTO_ITEM DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_EQUIPAMENTO DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_EQUIPAMENTO_HISTORICO_SERIE DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_EQUIPAMENTO_VS_CHIP DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_ESTOQUE_CHIP DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_ESTOQUE_EQUIPAMENTO DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_FINALIDADE DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_FOLLOW_UP DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_FORNECEDOR DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_LOJA DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_MARCA DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_MODELOS DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_MOTIVO DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_MOV_TRANSITO_CHIP DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_MOV_TRANSITO_EQUIPAMENTO DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_OCORRENCIA DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_OPERADORA DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_OS DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_OS_ITEM DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_PECA DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_PEDIDO_COMPRA_PECA DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_PEDIDO_COMPRA_PECA_ITEM DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_RESPONSAVEL DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_STATUS DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_STATUS_OS DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_TIPO_EQUIPAMENTO DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_TIPO_SERVICO DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_TRANSITO DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE CG_USUARIO DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE ROMANEIO_ESTOQUE DROP COLUMN ID_EMPRESA 
GO
ALTER TABLE ROMANEIO_ESTOQUE_ITEM DROP COLUMN ID_EMPRESA 
GO