--ALTER TABLE CG_TABELAS_PESQUISA_DINAMICA DROP CONSTRAINT DF_CG_TABELAS_PESQUISA_DINAMICA_EMPRESA

--ALTER TABLE  CG_TABELAS_PESQUISA_DINAMICA DROP COLUMN FILTRA_POR_EMPRESA
--GO
ALTER TABLE CG_TABELAS_PESQUISA_DINAMICA
ADD FILTRA_POR_EMPRESA BIT NOT NULL CONSTRAINT DF_CG_TABELAS_PESQUISA_DINAMICA_EMPRESA DEFAULT (1)
GO

UPDATE CG_TABELAS_PESQUISA_DINAMICA 
SET FILTRA_POR_EMPRESA = 0
WHERE TABELA NOT IN (
SELECT OBJECT_NAME(ID) AS TABELA FROM SYSCOLUMNS WHERE NAME = 'ID_EMPRESA')
GO