/* TABELA CG_LOJA: CHAVE UNICA PARA ID_EMPRESA + CODIGO */
IF EXISTS(SELECT 1 FROM [dbCG].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE CONSTRAINT_NAME = 'UNQ_CG_LOJA_CODIGO')
BEGIN
    ALTER TABLE CG_LOJA DROP CONSTRAINT UNQ_CG_LOJA_CODIGO
END
GO

/* TABELA CG_CHIP: CHAVE UNICA PARA ID_EMPRESA + SIMID */
IF EXISTS(SELECT 1 FROM [dbCG].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE CONSTRAINT_NAME = 'UNQ_CG_CHIP_SIMID')
BEGIN
    ALTER TABLE [dbo].[CG_CHIP] DROP CONSTRAINT [UNQ_CG_CHIP_SIMID]
END
GO

/* TABELA CG_AREA: CHAVE UNICA PARA ID_EMPRESA + DESC_AREA */
IF EXISTS(SELECT 1 FROM [dbCG].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE CONSTRAINT_NAME = 'UNQ_CG_AREA_DESC_AREA')
BEGIN
    ALTER TABLE [dbo].[CG_AREA] DROP CONSTRAINT UNQ_CG_AREA_DESC_AREA
END
GO

/* TABELA CG_MARCA: CHAVE UNICA PARA ID_EMPRESA + DESC_AREA */
IF EXISTS(SELECT 1 FROM [dbCG].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE CONSTRAINT_NAME = 'UNIQUE_CG_MARCA_1')
BEGIN
    ALTER TABLE [dbo].[CG_MARCA] DROP CONSTRAINT [UNIQUE_CG_MARCA_1]
END
GO


/* TABELA CG_FINALIDADE: CHAVE UNICA PARA ID_EMPRESA + DESC_FINALIDADE */
IF EXISTS(SELECT 1 FROM [dbCG].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE CONSTRAINT_NAME = 'UNIQUE_CG_FINALIDADE_1')
BEGIN
    ALTER TABLE [dbo].[CG_FINALIDADE] DROP CONSTRAINT [UNIQUE_CG_FINALIDADE_1]
END
GO

/* TABELA CG_CATEGORIA: CHAVE UNICA PARA ID_EMPRESA + DESC_CATEGORIA */
IF EXISTS(SELECT 1 FROM [dbCG].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE CONSTRAINT_NAME = 'UNIQUE_CG_CATEGORIA_1')
BEGIN
    ALTER TABLE [dbo].[CG_CATEGORIA] DROP CONSTRAINT [UNIQUE_CG_CATEGORIA_1]
END
GO


/* TABELA CG_PECA: CHAVE UNICA PARA ID_EMPRESA + NOME_PECA */
IF EXISTS(SELECT 1 FROM [dbCG].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE CONSTRAINT_NAME = 'UNIQUE_CG_PECA_1')
BEGIN
    ALTER TABLE [dbo].[CG_PECA] DROP CONSTRAINT [UNIQUE_CG_PECA_1]
END
GO