


/* TABELA CG_LOJA: CHAVE UNICA PARA ID_EMPRESA + CODIGO */
IF EXISTS(SELECT 1 FROM [dbCG].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE CONSTRAINT_NAME = 'UNQ_CG_LOJA_CODIGO')
BEGIN
    ALTER TABLE CG_LOJA DROP CONSTRAINT UNQ_CG_LOJA_CODIGO
END
GO

ALTER TABLE CG_LOJA
    ADD CONSTRAINT UNQ_CG_LOJA_CODIGO UNIQUE (ID_EMPRESA,CODIGO); 

GO

/* TABELA CG_CHIP: CHAVE UNICA PARA ID_EMPRESA + SIMID */
IF EXISTS(SELECT 1 FROM [dbCG].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE CONSTRAINT_NAME = 'UNQ_CG_CHIP_SIMID')
BEGIN
    ALTER TABLE [dbo].[CG_CHIP] DROP CONSTRAINT [UNQ_CG_CHIP_SIMID]
END
GO

ALTER TABLE [dbo].[CG_CHIP] 
ADD CONSTRAINT UNQ_CG_CHIP_SIMID UNIQUE (ID_EMPRESA,SIMID); 
GO

/* TABELA CG_AREA: CHAVE UNICA PARA ID_EMPRESA + DESC_AREA */
IF EXISTS(SELECT 1 FROM [dbCG].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE CONSTRAINT_NAME = 'UNQ_CG_AREA_DESC_AREA')
BEGIN
    ALTER TABLE [dbo].[CG_AREA] DROP CONSTRAINT UNQ_CG_AREA_DESC_AREA
END
GO

ALTER TABLE [dbo].[CG_AREA] 
ADD  CONSTRAINT [UNQ_CG_AREA_DESC_AREA] UNIQUE (ID_EMPRESA,DESC_AREA)
GO

/* TABELA CG_MARCA: CHAVE UNICA PARA ID_EMPRESA + DESC_AREA */
IF EXISTS(SELECT 1 FROM [dbCG].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE CONSTRAINT_NAME = 'UNIQUE_CG_MARCA_1')
BEGIN
    ALTER TABLE [dbo].[CG_MARCA] DROP CONSTRAINT [UNIQUE_CG_MARCA_1]
END
GO

ALTER TABLE [dbo].[CG_MARCA] 
ADD  CONSTRAINT [UNIQUE_CG_MARCA_1] UNIQUE (ID_EMPRESA,DESC_MARCA)
GO


/* TABELA CG_FINALIDADE: CHAVE UNICA PARA ID_EMPRESA + DESC_FINALIDADE */
IF EXISTS(SELECT 1 FROM [dbCG].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE CONSTRAINT_NAME = 'UNIQUE_CG_FINALIDADE_1')
BEGIN
    ALTER TABLE [dbo].[CG_FINALIDADE] DROP CONSTRAINT [UNIQUE_CG_FINALIDADE_1]
END
GO

ALTER TABLE [dbo].[CG_FINALIDADE] 
ADD  CONSTRAINT [UNIQUE_CG_FINALIDADE_1] UNIQUE (ID_EMPRESA,DESC_FINALIDADE)
GO

/* TABELA CG_CATEGORIA: CHAVE UNICA PARA ID_EMPRESA + DESC_CATEGORIA */
IF EXISTS(SELECT 1 FROM [dbCG].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE CONSTRAINT_NAME = 'UNIQUE_CG_CATEGORIA_1')
BEGIN
    ALTER TABLE [dbo].[CG_CATEGORIA] DROP CONSTRAINT [UNIQUE_CG_CATEGORIA_1]
END
GO


ALTER TABLE [dbo].[CG_CATEGORIA] 
ADD  CONSTRAINT [UNIQUE_CG_CATEGORIA_1] UNIQUE (ID_EMPRESA, DESC_CATEGORIA)
GO


/* TABELA CG_PECA: CHAVE UNICA PARA ID_EMPRESA + NOME_PECA */
IF EXISTS(SELECT 1 FROM [dbCG].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE CONSTRAINT_NAME = 'UNIQUE_CG_PECA_1')
BEGIN
    ALTER TABLE [dbo].[CG_PECA] DROP CONSTRAINT [UNIQUE_CG_PECA_1]
END
GO

ALTER TABLE [dbo].[CG_PECA] 
ADD  CONSTRAINT [UNIQUE_CG_PECA_1] UNIQUE (ID_EMPRESA,NOME_PECA)
GO