CREATE TABLE CG_TIPO_LOCAL_ESTOQUE (
ID_TIPO_LOCAL_ESTOQUE INT NOT NULL,
DESC_TIPO_LOCAL_ESTOQUE VARCHAR(50) NOT NULL)
GO

ALTER TABLE CG_TIPO_LOCAL_ESTOQUE 
ADD CONSTRAINT PK_CG_TIPO_LOCAL_ESTOQUE PRIMARY KEY (ID_TIPO_LOCAL_ESTOQUE) 
GO

INSERT INTO CG_TIPO_LOCAL_ESTOQUE (ID_TIPO_LOCAL_ESTOQUE, DESC_TIPO_LOCAL_ESTOQUE)
VALUES 
(0, 'NÃO ALOCADO'),
(1, 'MATRIZ'),
(2, 'ASSISTENCIA TECNICA'),
(7, 'QUARENTENA'),
(8, 'INATIVO'),
(9, 'DEVOLVEU FORNECEDOR'),
(10, 'LOJA FISICA')

