ALTER TABLE CG_LOJA 
ADD ID_TIPO_LOCAL_ESTOQUE INT NOT NULL DEFAULT (10) 
GO

ALTER TABLE CG_LOJA 
ADD CONSTRAINT FK_CG_TIPO_LOCAL_ESTOQUE_01
FOREIGN KEY (ID_TIPO_LOCAL_ESTOQUE) REFERENCES CG_TIPO_LOCAL_ESTOQUE (ID_TIPO_LOCAL_ESTOQUE)
GO


UPDATE CG_LOJA SET ID_TIPO_LOCAL_ESTOQUE = 0 WHERE ID_LOJA = 0;
UPDATE CG_LOJA SET ID_TIPO_LOCAL_ESTOQUE = 1 WHERE ID_LOJA = 1;
UPDATE CG_LOJA SET ID_TIPO_LOCAL_ESTOQUE = 2 WHERE ID_LOJA = 2;
UPDATE CG_LOJA SET ID_TIPO_LOCAL_ESTOQUE = 7 WHERE ID_LOJA = 7;
UPDATE CG_LOJA SET ID_TIPO_LOCAL_ESTOQUE = 8 WHERE ID_LOJA = 8;
UPDATE CG_LOJA SET ID_TIPO_LOCAL_ESTOQUE = 9 WHERE ID_LOJA = 9;


