ALTER TABLE CG_ACESSO ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_ALOCACAO ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_AREA ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_CARGO ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_CATEGORIA ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_CHIP ADD ID_EMPRESA INT NULL; 
GO
--ALTER TABLE CG_EMPRESA ADD ID_EMPRESA INT NULL; 
--GO
--ALTER TABLE CG_EMPRESA_VS_USUARIOS ADD ID_EMPRESA INT NULL; 
--GO
ALTER TABLE CG_ENTRADA_CHIP ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_ENTRADA_CHIP_ITEM ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_ENTRADA_EQUIPAMENTO ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_ENTRADA_EQUIPAMENTO_ITEM ADD ID_EMPRESA INT NULL; 
GO
--ALTER TABLE CG_ENTRADA_ESTOQUE ADD ID_EMPRESA INT NULL; 
--GO
ALTER TABLE CG_EQUIPAMENTO ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_EQUIPAMENTO_HISTORICO_SERIE ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_EQUIPAMENTO_VS_CHIP ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_ESTOQUE_CHIP ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_ESTOQUE_EQUIPAMENTO ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_FINALIDADE ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_FOLLOW_UP ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_FORNECEDOR ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_LOJA ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_MARCA ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_MODELOS ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_MOTIVO ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_MOV_TRANSITO_CHIP ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_MOV_TRANSITO_EQUIPAMENTO ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_OCORRENCIA ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_OPERADORA ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_OS ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_OS_ITEM ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_PECA ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_PEDIDO_COMPRA_PECA ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_PEDIDO_COMPRA_PECA_ITEM ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_RESPONSAVEL ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_STATUS ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_STATUS_OS ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_TIPO_EQUIPAMENTO ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_TIPO_SERVICO ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_TRANSITO ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE CG_USUARIO ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE ROMANEIO_ESTOQUE ADD ID_EMPRESA INT NULL; 
GO
ALTER TABLE ROMANEIO_ESTOQUE_ITEM ADD ID_EMPRESA INT NULL; 
GO

/* ATUALIZA ID_EMPRESA PARA 1 (EMPRESA MATRIZ) */
UPDATE CG_ACESSO SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_ALOCACAO SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_AREA SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_CARGO SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_CATEGORIA SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_CHIP SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_EMPRESA SET ID_EMPRESA = 1 WHERE 1=1;

--UPDATE CG_EMPRESA_VS_USUARIOS SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_ENTRADA_CHIP SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_ENTRADA_CHIP_ITEM SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_ENTRADA_EQUIPAMENTO SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_ENTRADA_EQUIPAMENTO_ITEM SET ID_EMPRESA = 1 WHERE 1=1;

--UPDATE CG_ENTRADA_ESTOQUE SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_EQUIPAMENTO SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_EQUIPAMENTO_HISTORICO_SERIE SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_EQUIPAMENTO_VS_CHIP SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_ESTOQUE_CHIP SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_ESTOQUE_EQUIPAMENTO SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_FINALIDADE SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_FOLLOW_UP SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_FORNECEDOR SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_LOJA SET ID_EMPRESA = 1, TELEFONE = ISNULL(TELEFONE,'-') WHERE 1=1;

UPDATE CG_MARCA SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_MODELOS SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_MOTIVO SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_MOV_TRANSITO_CHIP SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_MOV_TRANSITO_EQUIPAMENTO SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_OCORRENCIA SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_OPERADORA SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_OS SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_OS_ITEM SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_PECA SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_PEDIDO_COMPRA_PECA SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_PEDIDO_COMPRA_PECA_ITEM SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_RESPONSAVEL SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_STATUS SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_STATUS_OS SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_TIPO_EQUIPAMENTO SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_TIPO_SERVICO SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_TRANSITO SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE CG_USUARIO SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE ROMANEIO_ESTOQUE SET ID_EMPRESA = 1 WHERE 1=1;

UPDATE ROMANEIO_ESTOQUE_ITEM SET ID_EMPRESA = 1 WHERE 1=1;

/* MUDA AS COLUNAS ID_EMPRESA PARA NOT NULL */

ALTER TABLE CG_ACESSO ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_ALOCACAO ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_AREA ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_CARGO ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_CATEGORIA ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_CHIP ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
--ALTER TABLE CG_EMPRESA ALTER COLUMN ID_EMPRESA INT NOT NULL 
--GO
--ALTER TABLE CG_EMPRESA_VS_USUARIOS ALTER COLUMN ID_EMPRESA INT NOT NULL 
--GO
ALTER TABLE CG_ENTRADA_CHIP ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_ENTRADA_CHIP_ITEM ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_ENTRADA_EQUIPAMENTO ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_ENTRADA_EQUIPAMENTO_ITEM ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
--ALTER TABLE CG_ENTRADA_ESTOQUE ALTER COLUMN ID_EMPRESA INT NOT NULL 
--GO
ALTER TABLE CG_EQUIPAMENTO ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_EQUIPAMENTO_HISTORICO_SERIE ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_EQUIPAMENTO_VS_CHIP ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_ESTOQUE_CHIP ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_ESTOQUE_EQUIPAMENTO ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_FINALIDADE ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_FOLLOW_UP ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_FORNECEDOR ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_LOJA ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_MARCA ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_MODELOS ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_MOTIVO ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_MOV_TRANSITO_CHIP ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_MOV_TRANSITO_EQUIPAMENTO ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_OCORRENCIA ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_OPERADORA ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_OS ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_OS_ITEM ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_PECA ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_PEDIDO_COMPRA_PECA ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_PEDIDO_COMPRA_PECA_ITEM ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_RESPONSAVEL ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_STATUS ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_STATUS_OS ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_TIPO_EQUIPAMENTO ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_TIPO_SERVICO ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_TRANSITO ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE CG_USUARIO ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE ROMANEIO_ESTOQUE ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO
ALTER TABLE ROMANEIO_ESTOQUE_ITEM ALTER COLUMN ID_EMPRESA INT NOT NULL 
GO


