INSERT INTO CG_LOJA
select 
ID_LOJA+50 as ID_LOJA, 'LOJA '+CONVERT(VARCHAR,ID_LOJA+50) AS SIGLA, 'LOJA '+CONVERT(VARCHAR,ID_LOJA+50) AS NOME, ENDERECO, COMPLEMENTO, CEP, CIDADE, BAIRRO, UF, ID_TIPO_LOCAL, ID_RESPONSAVEL, USER_INS, DATA_INS, USER_UPD, DATA_UPD
from cg_loja where id_loja between 11 and 19


SELECT * FROM CG_LOJA ORDER BY ID_LOJA
