
INSERT INTO CG_EQUIPAMENTO (ID_EQUIPAMENTO, ID_TIPO_EQUIPAMENTO, DESC_EQUIPAMENTO, SERIE, MODELO, ID_FORNECEDOR, PROTOCOLO, VALOR, OBS, USER_INS, DATA_INS, USER_UPD, DATA_UPD, ID_LOCAL_ESTOQUE)
SELECT ID_CHIP AS ID_EQUIPAMENTO, 1 AS ID_TIPO_EQUIPAMENTO, 'POS - SIM:'+SIMID AS DESC_EQUIPAMENTO, SIMID AS SERIE, 'MODELO POS' AS MODELO, 20 AS ID_FORNECEDOR, '' AS PROTOCOLO, 100 AS VALOR, '' AS OBS, 1 AS USER_INS, GETDATE() AS DATA_INS, 1 AS USER_UPD, GETDATE() AS DATA_UPD, 0 AS ID_LOCAL_ESTOQUE
FROM CG_CHIP
