/*ZERAR MOVIMENTAÇÃO DE ESTOQUE*/

ALTER TABLE CG_MOVIMENTO_EQUIPAMENTO_ITEM
DISABLE TRIGGER ALL
GO

ALTER TABLE CG_MOVIMENTO_EQUIPAMENTO
DISABLE TRIGGER ALL
GO

ALTER TABLE CG_ENTRADA_EQUIPAMENTO_ITEM
DISABLE TRIGGER ALL
GO

ALTER TABLE CG_ENTRADA_EQUIPAMENTO
DISABLE TRIGGER ALL
GO

ALTER TABLE CG_DEVOLUCAO_EQUIPAMENTO_ITEM
DISABLE TRIGGER ALL
GO

ALTER TABLE CG_DEVOLUCAO_EQUIPAMENTO
DISABLE TRIGGER ALL
GO

ALTER TABLE CG_ESTOQUE_EQUIPAMENTO
DISABLE TRIGGER ALL
GO

/*
ALTER TABLE ROMANEIO_ESTOQUE_ITEM
DISABLE TRIGGER ALL
GO

ALTER TABLE ROMANEIO_ESTOQUE
DISABLE TRIGGER ALL
GO
*/

DELETE FROM CG_MOVIMENTO_EQUIPAMENTO_ITEM
GO

DELETE FROM CG_MOVIMENTO_EQUIPAMENTO
GO

DELETE FROM CG_ENTRADA_EQUIPAMENTO_ITEM
GO

DELETE FROM CG_ENTRADA_EQUIPAMENTO
GO

DELETE FROM CG_DEVOLUCAO_EQUIPAMENTO_ITEM
GO

DELETE FROM CG_DEVOLUCAO_EQUIPAMENTO
GO

DELETE FROM CG_ESTOQUE_EQUIPAMENTO
GO

/*
DELETE FROM ROMANEIO_ESTOQUE_ITEM
GO

DELETE FROM ROMANEIO_ESTOQUE
GO
*/

UPDATE CG_SEQUENCIAL SET KEYID = 0 
  WHERE TABELA IN ('CG_DEVOLUCAO_EQUIPAMENTO','CG_ENTRADA_EQUIPAMENTO','CG_MOVIMENTO_EQUIPAMENTO')
GO

UPDATE CG_EQUIPAMENTO SET ID_LOCAL_ESTOQUE = 0
GO

ALTER TABLE CG_MOVIMENTO_EQUIPAMENTO_ITEM
ENABLE TRIGGER ALL
GO

ALTER TABLE CG_MOVIMENTO_EQUIPAMENTO
ENABLE TRIGGER ALL
GO

ALTER TABLE CG_ENTRADA_EQUIPAMENTO_ITEM
ENABLE TRIGGER ALL
GO

ALTER TABLE CG_ENTRADA_EQUIPAMENTO
ENABLE TRIGGER ALL
GO

ALTER TABLE CG_DEVOLUCAO_EQUIPAMENTO_ITEM
ENABLE TRIGGER ALL
GO

ALTER TABLE CG_DEVOLUCAO_EQUIPAMENTO
ENABLE TRIGGER ALL
GO

ALTER TABLE CG_ESTOQUE_EQUIPAMENTO
ENABLE TRIGGER ALL
GO

/*
ALTER TABLE ROMANEIO_ESTOQUE_ITEM
ENABLE TRIGGER ALL
GO

ALTER TABLE ROMANEIO_ESTOQUE
ENABLE TRIGGER ALL
GO
*/