INSERT INTO CG_LOJA
(ID_LOJA, SIGLA, NOME, ID_TIPO_LOCAL, ID_RESPONSAVEL, USER_INS, DATA_INS)
VALUES 
(0, 'NAO ALOCADO', 'NAO ALOCADO', 1, 1, 1, GETDATE());

INSERT INTO CG_LOJA
(ID_LOJA, SIGLA, NOME, ID_TIPO_LOCAL, ID_RESPONSAVEL, USER_INS, DATA_INS)
VALUES 
(1, 'MATRIZ', 'MATRIZ', 1, 1, 1, GETDATE());

INSERT INTO CG_LOJA
(ID_LOJA, SIGLA, NOME, ID_TIPO_LOCAL, ID_RESPONSAVEL, USER_INS, DATA_INS)
VALUES 
(2, 'ASSISTENCIA TECNICA', 'ASSISTENCIA TECNICA', 1, 1, 1, GETDATE());

INSERT INTO CG_LOJA
(ID_LOJA, SIGLA, NOME, ID_TIPO_LOCAL, ID_RESPONSAVEL, USER_INS, DATA_INS)
VALUES 
(9, 'DEVOLVEU FORNECEDOR', 'DEVOLVEU FORNECEDOR', 1, 1, 1, GETDATE());

