INSERT INTO CG_EQUIPAMENTO 
(ID_EQUIPAMENTO, ID_TIPO_EQUIPAMENTO, DESC_EQUIPAMENTO, SERIE, MODELO, ID_FORNECEDOR, 
PROTOCOLO, VALOR, OBS, USER_INS, DATA_INS, USER_UPD, DATA_UPD, ESTOQUE_MATRIZ, ESTOQUE_TRANSITO, 
ESTOQUE_LOJA, ID_LOCAL_ESTOQUE)
SELECT 
    ROW_NUMBER() OVER(ORDER BY ID_CHIP ASC)  AS ID_EQUIPAMENTO, 
    1 AS ID_TIPO_EQUIPAMENTO, 
    'POS # '+CONVERT(VARCHAR,ROW_NUMBER()OVER(ORDER BY ID_CHIP ASC)) AS  DESC_EQUIPAMENTO, 
    'SN# '+LEFT(NEWID(),8) AS SERIE, 
    'MODELO PAYTEC 2016/1' AS MODELO, 
    20 AS ID_FORNECEDOR, 
    NULL AS PROTOCOLO, 
    100 AS VALOR, 
    NULL AS OBS, 
    1 AS USER_INS, 
    GETDATE() AS DATA_INS, 
    1 AS USER_UPD, 
    GETDATE() AS DATA_UPD, 
    1 AS ESTOQUE_MATRIZ, 
    0 AS ESTOQUE_TRANSITO, 
    0 AS ESTOQUE_LOJA, 
    0 AS ID_LOCAL_ESTOQUE
FROM CG_CHIP
