USE dbCG
GO

INSERT INTO CG_LOJA (ID_LOJA,SIGLA,NOME,ENDERECO,COMPLEMENTO,CEP,CIDADE,BAIRRO,UF,ID_TIPO_LOCAL,ID_RESPONSAVEL,USER_INS,DATA_INS,USER_UPD,DATA_UPD,TELEFONE,CELULAR,LOJA_FISICA,PARCERIA,ID_AREA,ID_EMPRESA,ID_TIPO_LOCAL_ESTOQUE,INATIVO,ULTIMA_ATUALIZACAO,INICIO_VIGENCIA,CODIGO)
VALUES
(3,'COM DEFEITO','COM DEFEITO','ENDERECO DA MATRIZ','','-','SAO PAULO','TATUAPE','SP',1,1,1,GETDATE(),1,GETDATE(),'-','-',0,0,'0000',1,3,0,GETDATE(),GETDATE(),'0003'),
(4,'LAUDO','LAUDO','ENDERECO DA MATRIZ','','-','SAO PAULO','TATUAPE','SP',1,1,1,GETDATE(),1,GETDATE(),'-','-',0,0,'0000',1,4,0,GETDATE(),GETDATE(),'0004'),
(5,'ESTOQUE PECAS','ESTOQUE PECAS','ENDERECO DA MATRIZ','','-','SAO PAULO','TATUAPE','SP',1,1,1,GETDATE(),1,GETDATE(),'-','-',0,0,'0000',1,5,0,GETDATE(),GETDATE(),'0005')
