CREATE PROCEDURE spTransfere_Estoque_POS
(
@ID_EQUIPAMENTO INT,
@QUANTIDADE INT,
@TRANSITO BIT,
@ID_LOCAL_PARA INT,
@TIPO_LOCAL CHAR(1),
@ID_EMPRESA INT
)
AS
UPDATE CG_ESTOQUE_EQUIPAMENTO SET
		estoque = @QUANTIDADE,
		transito = @transito,
		id_local = @ID_LOCAL_PARA,
		datamov = getdate(),
		TIPO_LOCAL=@TIPO_LOCAL
WHERE
		ID_EQUIPAMENTO = @ID_EQUIPAMENTO
GO
