CREATE TABLE CG_MOV_TRANSITO_CHIP (
ID_LANCTO BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ID_TRANSITO INT NOT NULL,
ID_ORIGEM INT NOT NULL,
ID_CHIP INT NOT NULL,
QUANTIDADE INT NOT NULL,
USER_INS INT NOT NULL,
DATA_LANCTO DATETIME NOT NULL,
ID_DESTINO INT NULL,
DATA_MOV_DESTINO DATETIME NULL )
GO

ALTER TABLE CG_MOV_TRANSITO_CHIP
ADD CONSTRAINT DF_DATA_LANCTO DEFAULT (GETDATE()) FOR DATA_LANCTO
GO

ALTER TABLE CG_MOV_TRANSITO_CHIP
ADD CONSTRAINT FK_ID_TRANSITO FOREIGN KEY (ID_TRANSITO) REFERENCES CG_TRANSITO (ID_TRANSITO)
GO

ALTER TABLE CG_MOV_TRANSITO_CHIP
ADD CONSTRAINT FK_ID_ORIGEM FOREIGN KEY (ID_ORIGEM) REFERENCES CG_LOJA (ID_LOJA)
GO

ALTER TABLE CG_MOV_TRANSITO_CHIP
ADD CONSTRAINT FK_ID_CHIP FOREIGN KEY (ID_CHIP) REFERENCES CG_CHIP (ID_CHIP)
GO

ALTER TABLE CG_MOV_TRANSITO_CHIP
ADD CONSTRAINT FK_ID_USER_INS FOREIGN KEY (USER_INS) REFERENCES CG_USUARIO (ID_USUARIO)
GO

ALTER TABLE CG_MOV_TRANSITO_CHIP
ADD CONSTRAINT FK_ID_DESTINO FOREIGN KEY (ID_DESTINO) REFERENCES CG_LOJA (ID_LOJA)
GO
