CREATE TABLE CG_MOV_TRANSITO_EQUIPAMENTO (
ID_LANCTO BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ID_TRANSITO INT NOT NULL,
ID_ORIGEM INT NOT NULL,
ID_EQUIPAMENTO INT NOT NULL,
QUANTIDADE INT NOT NULL,
USER_INS INT NOT NULL,
DATA_LANCTO DATETIME NOT NULL,
ID_DESTINO INT NULL,
DATA_MOV_DESTINO DATETIME NULL )
GO

ALTER TABLE CG_MOV_TRANSITO_EQUIPAMENTO
ADD CONSTRAINT DF_DATA_LANCTO_2 DEFAULT (GETDATE()) FOR DATA_LANCTO
GO

ALTER TABLE CG_MOV_TRANSITO_EQUIPAMENTO
ADD CONSTRAINT FK_ID_TRANSITO_2 FOREIGN KEY (ID_TRANSITO) REFERENCES CG_TRANSITO (ID_TRANSITO)
GO

ALTER TABLE CG_MOV_TRANSITO_EQUIPAMENTO
ADD CONSTRAINT FK_ID_ORIGEM_2 FOREIGN KEY (ID_ORIGEM) REFERENCES CG_LOJA (ID_LOJA)
GO

ALTER TABLE CG_MOV_TRANSITO_EQUIPAMENTO
ADD CONSTRAINT FK_ID_EQUIPAMENTO_2 FOREIGN KEY (ID_EQUIPAMENTO) REFERENCES CG_EQUIPAMENTO (ID_EQUIPAMENTO)
GO

ALTER TABLE CG_MOV_TRANSITO_EQUIPAMENTO
ADD CONSTRAINT FK_ID_USER_INS_2 FOREIGN KEY (USER_INS) REFERENCES CG_USUARIO (ID_USUARIO)
GO

ALTER TABLE CG_MOV_TRANSITO_EQUIPAMENTO
ADD CONSTRAINT FK_ID_DESTINO_2 FOREIGN KEY (ID_DESTINO) REFERENCES CG_LOJA (ID_LOJA)
GO
