USE [dbCG]
GO

/****** Object:  View [dbo].[VW_CG_ESTOQUE_EQUIPAMENTO]    Script Date: 03/11/2018 08:25:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_CG_ESTOQUE_EQUIPAMENTO]
AS
SELECT
    A.ID_EQUIPAMENTO, 
    B.SERIE, 
    B.MODELO, 
    B.DESC_EQUIPAMENTO, 
    A.ESTOQUE, 
    A.TRANSITO, 
    B.VALOR, 
    A.ID_LOCAL, 
    L.NOME, 
    L.SIGLA,
    A.DATAMOV, 
    B.ID_LOCAL_ESTOQUE,
    L.CODIGO,
    L.LOJA_FISICA,
    L.ID_AREA,
    A.TIPO_LOCAL,
	A.ID_EMPRESA,
	(select top 1 id_os 
	from VW_CG_OS_ITEM 
	where isnull(DATA_RETORNO,'')='' 
	and ID_EQUIPAMENTO = a.ID_EQUIPAMENTO 
	order by id_os desc) as ID_OS
    
FROM
    dbo.CG_ESTOQUE_EQUIPAMENTO AS A 
	   INNER JOIN
		  dbo.CG_EQUIPAMENTO AS B 
			 ON A.ID_EQUIPAMENTO = B.ID_EQUIPAMENTO
	   LEFT JOIN (
			 SELECT 'T' AS TIPO_LOCAL, ID_TRANSITO AS ID_LOJA, 
			 NOME_TRANSITO AS SIGLA, NOME_TRANSITO AS NOME, 
			 CONVERT(VARCHAR,ID_TRANSITO) AS CODIGO, 
			 CAST(0 AS BIT ) AS LOJA_FISICA,
			 SPACE(8) AS ID_AREA FROM CG_TRANSITO
			 UNION 
			 --SELECT 'L' AS TIPO_LOCAL, 0 AS ID_LOJA, 'NÃO ALOCADO' AS SIGLA, 'NÃO ALOCADO' AS NOME, SPACE(10) AS CODIGO
			 --UNION 
			 SELECT 'L' AS TIPO_LOCAL, ID_LOJA, SIGLA, NOME, 
			 CODIGO, LOJA_FISICA, ID_AREA FROM CG_LOJA ) AS L 
				ON L.ID_LOJA = A.ID_LOCAL AND L.TIPO_LOCAL = A.TIPO_LOCAL


GO


