CREATE VIEW VW_CG_PEDIDOVENDA
AS
select 
		a.ID_PEDIDO, 
		a.STATUS_PEDIDO, 
		a.ID_CLIENTE, 
		b.NOME,
		a.DATA, 
		a.PREVISAO_ENTREGA, 
		a.DATA_BAIXA, 
		a.TOT_QTDE_ORIGINAL, 
		a.TOT_QTDE_ENTREGAR, 
		a.ULTIMA_ALTERACAO
from CG_PEDIDOVENDA a
inner join CG_CLIENTE b 
		ON b.ID_CLIENTE=a.ID_CLIENTE
